### ISSUE TITLE
OSX runtime issue when using library

### ISSUE THREAD

**Issue by jhaynie** [lloyd/node-memwatch#11]
I'm trying to use on node 0.8.0 on OSX Snow Leopard and I get the following error when i attempt to use it.

```
Error: dlopen(/usr/local/lib/node_modules/memwatch/build/Release/memwatch.node, 1): no suitable image found.  Did find:
    /usr/local/lib/node_modules/memwatch/build/Release/memwatch.node: mach-o, but wrong architecture
    at Object.Module._extensions..node (module.js:480:11)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/memwatch/include.js:2:9)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

I've installed the module globally using npm and got no errors.  Here is the output log from install.

```
Jeff-Haynies-MacBook-Air:nettle jhaynie$ sudo npm install memwatch -g
npm http GET https://registry.npmjs.org/memwatch
npm http 304 https://registry.npmjs.org/memwatch

> memwatch@0.1.3 install /usr/local/lib/node_modules/memwatch
> make build

rm -Rf build
node-waf configure
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for program gcc or cc           : /usr/bin/gcc 
Checking for gcc                         : ok  
Checking for node path                   : ok /Users/jhaynie/.node_libraries 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.317s)
node-waf build
Waf: Entering directory `/usr/local/lib/node_modules/memwatch/build'
[1/5] cxx: src/memwatch.cc -> build/Release/src/memwatch_1.o
[2/5] cxx: src/heapdiff.cc -> build/Release/src/heapdiff_1.o
[3/5] cxx: src/util.cc -> build/Release/src/util_1.o
[4/5] cxx: src/init.cc -> build/Release/src/init_1.o
[5/5] cxx_link: build/Release/src/memwatch_1.o build/Release/src/heapdiff_1.o build/Release/src/util_1.o build/Release/src/init_1.o -> build/Release/memwatch.node
Waf: Leaving directory `/usr/local/lib/node_modules/memwatch/build'
'build' finished successfully (3.531s)
memwatch@0.1.3 /usr/local/lib/node_modules/memwatch
```

When I run `file` against the file i get:

```
Jeff-Haynies-MacBook-Air:nettle jhaynie$  file /usr/local/lib/node_modules/memwatch/build/Release/memwatch.node
/usr/local/lib/node_modules/memwatch/build/Release/memwatch.node: Mach-O bundle i386
```

Here is some more info about node:

```
Jeff-Haynies-MacBook-Air:nettle jhaynie$ node
> process.arch
'x64'
> process.versions
{ http_parser: '1.0',
  node: '0.8.0',
  v8: '3.11.10.10',
  ares: '1.7.5-DEV',
  uv: '0.8',
  zlib: '1.2.3',
  openssl: '1.0.0f' }
```

Any ideas how to resolve this?

**Comment by jhaynie** [comment]
Send pull request that seems to fix this issue.  https://github.com/lloyd/node-memwatch/pull/12

**Comment by lloyd** [comment]
closing down, PR merged.  please double check with memwatch 0.1.4 and confirm it builds for you?
