### ISSUE TITLE
npm install fails on CentOS 5.7

### ISSUE THREAD

**Issue by AndrewForth** [lloyd/node-memwatch#18]
I am using Node version 0.8.6. Here is the output when I try to install memwatch:

> memwatch@0.2.0 install /home/aforth/code/noschema/api/node_modules/memwatch
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Command failed: Unknown option: --
gyp ERR! stack usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
gyp ERR! stack Try `python -h' for more information.
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:536:15)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:91:17)
gyp ERR! stack     at maybeClose (child_process.js:634:16)
gyp ERR! stack     at Socket.ChildProcess.spawn.stdin (child_process.js:806:11)
gyp ERR! stack     at Socket.EventEmitter.emit (events.js:88:17)
gyp ERR! stack     at Socket._destroy.destroyed (net.js:356:10)
gyp ERR! stack     at process.startup.processNextTick.process._tickCallback (node.js:244:9)
gyp ERR! System Linux 2.6.18-274.el5
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/aforth/code/noschema/api/node_modules/memwatch
gyp ERR! node -v v0.8.6
gyp ERR! node-gyp -v v0.6.3
gyp ERR! not ok 
npm ERR! memwatch@0.2.0 install:`node-gyp rebuild`
npm ERR!`sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the memwatch@0.2.0 install script.
npm ERR! This is most likely a problem with the memwatch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls memwatch
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.18-274.el5
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "memwatch"
npm ERR! cwd /home/aforth/code/noschema/api/node_modules
npm ERR! node -v v0.8.6
npm ERR! npm -v 1.1.48
npm ERR! code ELIFECYCLE

---

Thank you.

**Comment by lloyd** [comment]
this looks like a gyp bug.  can you try updating node and see if the problem persists?
