### ISSUE TITLE
Install fails in Ubuntu 12.04 (32 bit)

### ISSUE THREAD

**Issue by feklee** [lloyd/node-memwatch#20]
```
$ npm install memwatch
npm http GET https://registry.npmjs.org/memwatch
npm http 304 https://registry.npmjs.org/memwatch

> memwatch@0.2.0 install /scratch/rotogamesq_debug/node_modules/memwatch
> node-gyp rebuild

make: Entering directory `/scratch/rotogamesq_debug/node_modules/memwatch/build'
make: Warning: File `../binding.gyp' has modification time 6.5e+05 s in the future
  ACTION Regenerating Makefile
Traceback (most recent call last):
  File "/home/felix/.node-gyp/0.8.14/tools/gyp/gyp", line 18, in <module>
    sys.exit(gyp.main(sys.argv[1:]))
  File "/home/felix/.node-gyp/0.8.14/tools/gyp/pylib/gyp/__init__.py", line 511, in main
    return gyp_main(args)
  File "/home/felix/.node-gyp/0.8.14/tools/gyp/pylib/gyp/__init__.py", line 494, in gyp_main
    options.circular_check)
  File "/home/felix/.node-gyp/0.8.14/tools/gyp/pylib/gyp/__init__.py", line 133, in Load
    depth, generator_input_info, check, circular_check)
  File "/home/felix/.node-gyp/0.8.14/tools/gyp/pylib/gyp/input.py", line 2378, in Load
    depth, check)
  File "/home/felix/.node-gyp/0.8.14/tools/gyp/pylib/gyp/input.py", line 358, in LoadTargetBuildFile
    includes, True, check)
  File "/home/felix/.node-gyp/0.8.14/tools/gyp/pylib/gyp/input.py", line 208, in LoadOneBuildFile
    raise Exception("%s not found (cwd: %s)" % (build_file_path, os.getcwd()))
Exception: binding.gyp not found (cwd: /scratch/rotogamesq_debug/node_modules/memwatch/build) while trying to load binding.gyp
make: *** [Makefile] Error 1
make: Leaving directory `/scratch/rotogamesq_debug/node_modules/memwatch/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/nodejs/npm/node_modules/node-gyp/lib/build.js:236:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Linux 3.2.0-32-generic
gyp ERR! command "node" "/usr/lib/nodejs/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /scratch/rotogamesq_debug/node_modules/memwatch
gyp ERR! node -v v0.8.14
gyp ERR! node-gyp -v v0.7.1
gyp ERR! not ok 
npm ERR! memwatch@0.2.0 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the memwatch@0.2.0 install script.
npm ERR! This is most likely a problem with the memwatch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls memwatch
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.2.0-32-generic
npm ERR! command "nodejs" "/usr/bin/npm" "install" "memwatch"
npm ERR! cwd /scratch/rotogamesq_debug
npm ERR! node -v v0.8.14
npm ERR! npm -v 1.1.65
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /scratch/rotogamesq_debug/npm-debug.log
npm ERR! not ok code 0
```

**Comment by feklee** [comment]
I now did an upgrade to Ubuntu 12.10, and - surprise, surprise - _memwatch_ installs fine!

**Comment by lloyd** [comment]
are you in a position to retry with 12.04 and memwatch 0.2.1?  if not, let's close this and wait for someone else to complain.  I'm blindly hoping that the bindings upgrade required for 0.10.0 support fixed this :hamburger:

**Comment by lloyd** [comment]
(closing for now, please re-open if you can still reproduce and can confirm that v0.2.1 is still broken)
