### ISSUE TITLE
npm update: error: no matching function for call to 'uv_queue_work'

### ISSUE THREAD

**Issue by webjay** [lloyd/node-memwatch#31]
node -v = v0.10.0
npm -v = 1.2.14

`npm update` gives me:

```
npm http 304 https://registry.npmjs.org/memwatch/0.1.5

> memwatch@0.1.5 install /Users/jacob/Sites/Konfect/node_modules/nodefly/node_modules/memwatch
> node-gyp rebuild

  CXX(target) Release/obj.target/memwatch/src/heapdiff.o
  CXX(target) Release/obj.target/memwatch/src/init.o
  CXX(target) Release/obj.target/memwatch/src/memwatch.o
../src/memwatch.cc:227:5: error: no matching function for call to 'uv_queue_work'
    uv_queue_work(uv_default_loop(), &(baton->req), NULL, AsyncMemwatchAfter);
    ^~~~~~~~~~~~~
/Users/jacob/.node-gyp/0.10.0/deps/uv/include/uv.h:1397:15: note: candidate function not viable: no known conversion from
      'void (uv_work_t *)' to 'uv_after_work_cb' (aka 'void (*)(uv_work_t *, int)') for 4th argument
UV_EXTERN int uv_queue_work(uv_loop_t* loop, uv_work_t* req,
              ^
1 error generated.
make: *** [Release/obj.target/memwatch/src/memwatch.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/0.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:256:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:754:12)
gyp ERR! System Darwin 12.2.1
gyp ERR! command "node" "/usr/local/Cellar/node/0.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jacob/Sites/Konfect/node_modules/nodefly/node_modules/memwatch
gyp ERR! node -v v0.10.0
gyp ERR! node-gyp -v v0.8.5
gyp ERR! not ok 
npm WARN optional dep failed, continuing memwatch@0.1.5
```

When I try `npm install memwatch` I get:

```
npm http GET https://registry.npmjs.org/memwatch
npm http 304 https://registry.npmjs.org/memwatch
npm http GET https://registry.npmjs.org/memwatch/-/memwatch-0.2.0.tgz
npm http 200 https://registry.npmjs.org/memwatch/-/memwatch-0.2.0.tgz

> memwatch@0.2.0 install /Users/jacob/Sites/Konfect/node_modules/memwatch
> node-gyp rebuild

  CXX(target) Release/obj.target/memwatch/src/heapdiff.o
  CXX(target) Release/obj.target/memwatch/src/init.o
  CXX(target) Release/obj.target/memwatch/src/memwatch.o
../src/memwatch.cc:227:5: error: no matching function for call to 'uv_queue_work'
    uv_queue_work(uv_default_loop(), &(baton->req), NULL, AsyncMemwatchAfter);
    ^~~~~~~~~~~~~
/Users/jacob/.node-gyp/0.10.0/deps/uv/include/uv.h:1397:15: note: candidate function not viable: no known conversion from
      'void (uv_work_t *)' to 'uv_after_work_cb' (aka 'void (*)(uv_work_t *, int)') for 4th argument
UV_EXTERN int uv_queue_work(uv_loop_t* loop, uv_work_t* req,
              ^
1 error generated.
make: *** [Release/obj.target/memwatch/src/memwatch.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/0.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:256:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:754:12)
gyp ERR! System Darwin 12.2.1
gyp ERR! command "node" "/usr/local/Cellar/node/0.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jacob/Sites/Konfect/node_modules/memwatch
gyp ERR! node -v v0.10.0
gyp ERR! node-gyp -v v0.8.5
gyp ERR! not ok 
npm ERR! memwatch@0.2.0 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the memwatch@0.2.0 install script.
npm ERR! This is most likely a problem with the memwatch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls memwatch
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.2.1
npm ERR! command "/usr/local/Cellar/node/0.10.0/bin/node" "/usr/local/bin/npm" "install" "memwatch"
npm ERR! cwd /Users/jacob/Sites/Konfect
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/jacob/Sites/Konfect/npm-debug.log
npm ERR! not ok code 0
```

**Comment by lloyd** [comment]
should be fixed in memwatch 0.2.1, available now from your favorite npm server.
