### ISSUE TITLE
npm install fail on mac 

### ISSUE THREAD

**Issue by khwaja** [lloyd/node-memwatch#33]
npm http GET https://registry.npmjs.org/memwatch
npm http 304 https://registry.npmjs.org/memwatch

> memwatch@0.2.2 install /Applications/hammersmith/khwaja/delApiKey/hs-web-service/hs-web-service/node_modules/memwatch
> node-gyp rebuild

  CXX(target) Release/obj.target/memwatch/src/heapdiff.o
make: c++: No such file or directory
make: **\* [Release/obj.target/memwatch/src/heapdiff.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:255:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Darwin 12.2.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Applications/hammersmith/khwaja/delApiKey/hs-web-service/hs-web-service/node_modules/memwatch
gyp ERR! node -v v0.8.18
gyp ERR! node-gyp -v v0.8.2
gyp ERR! not ok 
npm ERR! memwatch@0.2.2 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the memwatch@0.2.2 install script.
npm ERR! This is most likely a problem with the memwatch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls memwatch
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "memwatch"
npm ERR! cwd /Applications/hammersmith/khwaja/delApiKey/hs-web-service/hs-web-service/node_modules
npm ERR! node -v v0.8.18
npm ERR! npm -v 1.2.2
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Applications/hammersmith/khwaja/delApiKey/hs-web-service/hs-web-service/node_modules/npm-debug.log
npm ERR! not ok code 0

**Comment by khwaja** [comment]
After setting the the environment variable CPLUS_INCLUDE_PATH and LIBRARY_PATH, npm install pass.

**Comment by smcelhinney** [comment]
My issue was an old version of Node. I upgraded using npm (details here: http://davidwalsh.name/upgrade-nodejs) - worked fine after that.

**Comment by dexdexdex** [comment]
I had a very similar thing happen to me. It turns out after I downloaded and installed xcode everything was fine.
