### ISSUE TITLE
build fails on windows vista visual c++ 2008 installed node 10.13

### ISSUE THREAD

**Issue by jsdevel** [lloyd/node-memwatch#48]
Here's the output:

```
C:\Users\Joseph Spencer\node-java\node_modules\memwatch>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebu
ild
c:\users\joseph spencer\.node-gyp\0.10.23\deps\v8\include\v8.h(218): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handl
e<T>)'
C:\Program Files\Microsoft Visual Studio 9.0\vc\include\xlocale(342): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
C:\Program Files\Microsoft Visual Studio 9.0\vc\include\xlocale(342): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
..\src\memwatch.cc(72): warning C4244: 'initializing' : conversion from 'time_t' to 'size_t', possible loss of data
..\src\memwatch.cc(73): warning C4244: 'initializing' : conversion from 'time_t' to 'int', possible loss of data
..\src\memwatch.cc(74): warning C4244: 'initializing' : conversion from 'time_t' to 'int', possible loss of data
..\src\memwatch.cc(84): warning C4244: 'argument' : conversion from 'double' to 'int', possible loss of data
..\src\memwatch.cc(147): warning C4244: '=' : conversion from 'double' to 'unsigned int', possible loss of data
..\src\memwatch.cc(152): warning C4244: '=' : conversion from 'double' to 'unsigned int', possible loss of data
..\src\memwatch.cc(159): warning C4244: '=' : conversion from 'double' to 'unsigned int', possible loss of data
c:\users\joseph spencer\.node-gyp\0.10.23\deps\v8\include\v8.h(184): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handl
e<T>)'
C:\Program Files\Microsoft Visual Studio 9.0\vc\include\xlocale(342): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
..\src\heapdiff.cc(279): warning C4244: 'argument' : conversion from 'unsigned __int64' to 'v8::SnapshotObjectId', possible loss of data
..\src\heapdiff.cc(291): warning C4244: 'argument' : conversion from 'unsigned __int64' to 'v8::SnapshotObjectId', possible loss of data
C:\Program Files\Microsoft Visual Studio 9.0\vc\include\vector(46): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle
<T>)'
LINK : fatal error LNK1181: cannot open input file 'C:\Users\Joseph.obj'
Project : warning PRJ0018: The following environment variables were not found:
gyp ERR! build error
gyp ERR! stack Error: `c:\Windows\Microsoft.NET\Framework\v3.5\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Windows_NT 6.0.6000
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Joseph Spencer\node-java\node_modules\memwatch
gyp ERR! node -v v0.10.23
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok
npm ERR! memwatch@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the memwatch@0.2.2 install script.
npm ERR! This is most likely a problem with the memwatch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls memwatch
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.0.6000
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\Joseph Spencer\node-java
npm ERR! node -v v0.10.23
npm ERR! npm -v 1.3.17
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Joseph Spencer\node-java\npm-debug.log
npm ERR! not ok code 0

C:\Users\Joseph Spencer\node-java>
```

**Comment by leonardjaviniar** [comment]
I am also experiencing the same problem.
