### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by yaru22** [lloyd/node-memwatch#49]
I added `memwatch` to package.json and ran `npm install`. When I tried to execute a script that uses `memwatch` I got the following error:

```
module.js:349
  Module._extensions[extension](this, filename);
                               ^
Error: Module version mismatch. Expected 13, got 11.
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/Users/brianpark/workspace/test/node_modules/memwatch/include.js:2:9)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
```

So I deleted `node_modules` and tried `npm install` again from scratch but I still get the same error.

I'm using Mac OS X 10.7.5 and my node version is **v0.10.24**. Does anybody else have this problem? What is the fix or a workaround?

**Comment by rashthedude** [comment]
Hi, I have encountered a similar issue using memwatch 0.2.0 then tried upgrading from node 0.8.26 to 0.10.0 and now it's showing me the same error.
