### ISSUE TITLE
Installing on CentOS 6, node-gyp rebuild error

### ISSUE THREAD

**Issue by furqansiddiqui** [lloyd/node-memwatch#63]
When trying to install memwatch using "npm install memwatch", I get this error:

I have CentOS6 with python 2.6.6 installed on server.

> memwatch@0.2.2 install /home/[[username]]/public_html/sockets/node_modules/memwatch
> node-gyp rebuild
> 
> gyp WARN install got an error, rolling back install
> gyp ERR! configure error
> gyp ERR! stack Error: connect ETIMEDOUT
> gyp ERR! stack     at errnoException (net.js:905:11)
> gyp ERR! stack     at Object.afterConnect [as oncomplete](net.js:896:19)
> gyp ERR! System Linux 2.6.32-504.3.3.el6.x86_64
> gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/[[username]]/public_html/sockets/node_modules/memwatch
> gyp ERR! node -v v0.10.36
> gyp ERR! node-gyp -v v1.0.1
> gyp ERR! not ok
> 
> npm ERR! memwatch@0.2.2 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the memwatch@0.2.2 install script.
> npm ERR! This is most likely a problem with the memwatch package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls memwatch
> npm ERR! There is likely additional logging output above.
> npm ERR! System Linux 2.6.32-504.3.3.el6.x86_64
> npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "memwatch"
> npm ERR! cwd /home/[[username]]/public_html/sockets
> npm ERR! node -v v0.10.36
> npm ERR! npm -v 1.4.28
> npm ERR! code ELIFECYCLE
> npm ERR! not ok code 0

**Comment by cruvitaDev** [comment]
Same here, same setup. Taking it out of my build process for the time being.

**Comment by mateeyow** [comment]
+1

**Comment by guarilha** [comment]
I had a similar problem with Fedora 22. 

```
memwatch.target.mk:86: recipe for target 'Release/obj.target/memwatch/src/heapdiff.o' failed
make: *** [Release/obj.target/memwatch/src/heapdiff.o] Error 1
make: Leaving directory '/home/user/workspace/github/socket-pouch/node_modules/memwatch/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack at ChildProcess.emit (events.js:110:17)
gyp ERR! stack at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 4.0.4-301.fc22.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/workspace/github/socket-pouch/node_modules/memwatch
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 4.0.4-301.fc22.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "memwatch"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
```

**Comment by pedro-lucas** [comment]
+1

**Comment by fatmatto** [comment]
+1, I have same problem on ubuntu 15.04

```
npm WARN package.json mandrill-api@1.0.45 No README data
-
> memwatch@0.2.2 install /home/fat/Projects/proj/api/node_modules/memwatch
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/home/fat/Projects/Proj/api/node_modules/memwatch/build'
  CXX(target) Release/obj.target/memwatch/src/heapdiff.o
In file included from ../src/heapdiff.cc:5:0:
../src/heapdiff.hh:15:5: error: expected class-name before ‘{’ token
     {
     ^
../src/heapdiff.hh:19:53: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> New( const v8::Arguments& args );
                                                     ^
../src/heapdiff.hh:20:53: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> End( const v8::Arguments& args );
                                                     ^
../src/heapdiff.cc: In constructor ‘heapdiff::HeapDiff::HeapDiff()’:
../src/heapdiff.cc:30:34: error: class ‘heapdiff::HeapDiff’ does not have any field named ‘ObjectWrap’
 heapdiff::HeapDiff::HeapDiff() : ObjectWrap(), before(NULL), after(NULL),
                                  ^
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h: In static member function ‘static void heapdiff::HeapDiff::Initialize(v8::Handle<v8::Object>)’:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/heapdiff.cc:51:21: error: within this context
     v8::HandleScope scope;
                     ^
../src/heapdiff.cc:52:70: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     v8::Local<v8::FunctionTemplate> t = v8::FunctionTemplate::New(New);
                                                                      ^
../src/heapdiff.cc:52:70: note: candidate is:
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
../src/heapdiff.cc:54:21: error: ‘NewSymbol’ is not a member of ‘v8::String’
     t->SetClassName(String::NewSymbol("HeapDiff"));
                     ^
../src/heapdiff.cc:56:44: error: invalid conversion from ‘v8::Handle<v8::Value> (*)(const int&)’ to ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’ [-fpermissive]
     NODE_SET_PROTOTYPE_METHOD(t, "end", End);
                                            ^
In file included from ../src/heapdiff.hh:10:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/src/node.h:244:13: note: initializing argument 3 of ‘void node::NODE_SET_PROTOTYPE_METHOD(v8::Handle<v8::FunctionTemplate>, const char*, v8::FunctionCallback)’
 inline void NODE_SET_PROTOTYPE_METHOD(v8::Handle<v8::FunctionTemplate> recv,
             ^
../src/heapdiff.cc:58:17: error: ‘NewSymbol’ is not a member of ‘v8::String’
     target->Set(v8::String::NewSymbol( "HeapDiff"), t->GetFunction());
                 ^
../src/heapdiff.cc: At global scope:
../src/heapdiff.cc:62:36: error: ‘Arguments’ in namespace ‘v8’ does not name a type
 heapdiff::HeapDiff::New (const v8::Arguments& args)
                                    ^
../src/heapdiff.cc: In static member function ‘static v8::Handle<v8::Value> heapdiff::HeapDiff::New(const int&)’:
../src/heapdiff.cc:67:15: error: request for member ‘IsConstructCall’ in ‘args’, which is of non-class type ‘const int’
     if (!args.IsConstructCall()) {
               ^
../src/heapdiff.cc:70:17: error: ‘New’ is not a member of ‘v8::String’
                 String::New("Use the new operator to create instances of this object.")));
                 ^
../src/heapdiff.cc:70:89: error: ‘ThrowException’ was not declared in this scope
                 String::New("Use the new operator to create instances of this object.")));
                                                                                         ^
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/heapdiff.cc:73:21: error: within this context
     v8::HandleScope scope;
                     ^
../src/heapdiff.cc:77:11: error: ‘class heapdiff::HeapDiff’ has no member named ‘Wrap’
     self->Wrap(args.This());
           ^
../src/heapdiff.cc:77:21: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
     self->Wrap(args.This());
                     ^
../src/heapdiff.cc:82:20: error: ‘TakeSnapshot’ is not a member of ‘v8::HeapProfiler’
     self->before = v8::HeapProfiler::TakeSnapshot(v8::String::New(""));
                    ^
../src/heapdiff.cc:82:51: error: ‘New’ is not a member of ‘v8::String’
     self->before = v8::HeapProfiler::TakeSnapshot(v8::String::New(""));
                                                   ^
../src/heapdiff.cc:85:17: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
     return args.This();
                 ^
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘void buildIDSet(std::set<long unsigned int>*, const v8::HeapGraphNode*, int&)’:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/heapdiff.cc:97:21: error: within this context
     v8::HandleScope scope;
                     ^
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> changesetToObject(changeset&)’:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/heapdiff.cc:213:21: error: within this context
     v8::HandleScope scope;
                     ^
../src/heapdiff.cc:214:33: error: no matching function for call to ‘v8::Array::New()’
     Local<Array> a = Array::New();
                                 ^
../src/heapdiff.cc:214:33: note: candidate is:
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2417:23: note: static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)
   static Local<Array> New(Isolate* isolate, int length = 0);
                       ^
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2417:23: note:   candidate expects 2 arguments, 0 provided
../src/heapdiff.cc:217:39: error: no matching function for call to ‘v8::Object::New()’
         Local<Object> d = Object::New();
                                       ^
../src/heapdiff.cc:217:39: note: candidate is:
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:24: note: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:24: note:   candidate expects 1 argument, 0 provided
../src/heapdiff.cc:218:16: error: ‘New’ is not a member of ‘v8::String’
         d->Set(String::New("what"), String::New(i->first.c_str()));
                ^
../src/heapdiff.cc:218:37: error: ‘New’ is not a member of ‘v8::String’
         d->Set(String::New("what"), String::New(i->first.c_str()));
                                     ^
../src/heapdiff.cc:219:16: error: ‘New’ is not a member of ‘v8::String’
         d->Set(String::New("size_bytes"), Integer::New(i->second.size));
                ^
../src/heapdiff.cc:219:70: error: no matching function for call to ‘v8::Integer::New(long int&)’
         d->Set(String::New("size_bytes"), Integer::New(i->second.size));
                                                                      ^
../src/heapdiff.cc:219:70: note: candidate is:
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
../src/heapdiff.cc:220:16: error: ‘New’ is not a member of ‘v8::String’
         d->Set(String::New("size"), String::New(mw_util::niceSize(i->second.size).c_str()));
                ^
../src/heapdiff.cc:220:37: error: ‘New’ is not a member of ‘v8::String’
         d->Set(String::New("size"), String::New(mw_util::niceSize(i->second.size).c_str()));
                                     ^
../src/heapdiff.cc:221:16: error: ‘New’ is not a member of ‘v8::String’
         d->Set(String::New("+"), Integer::New(i->second.added));
                ^
../src/heapdiff.cc:221:62: error: no matching function for call to ‘v8::Integer::New(long int&)’
         d->Set(String::New("+"), Integer::New(i->second.added));
                                                              ^
../src/heapdiff.cc:221:62: note: candidate is:
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
../src/heapdiff.cc:222:16: error: ‘New’ is not a member of ‘v8::String’
         d->Set(String::New("-"), Integer::New(i->second.released));
                ^
../src/heapdiff.cc:222:65: error: no matching function for call to ‘v8::Integer::New(long int&)’
         d->Set(String::New("-"), Integer::New(i->second.released));
                                                                 ^
../src/heapdiff.cc:222:65: note: candidate is:
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
../src/heapdiff.cc:226:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(a);
                  ^
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> compare(const v8::HeapSnapshot*, const v8::HeapSnapshot*)’:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/heapdiff.cc:233:21: error: within this context
     v8::HandleScope scope;
                     ^
../src/heapdiff.cc:236:35: error: no matching function for call to ‘v8::Object::New()’
     Local<Object> o = Object::New();
                                   ^
../src/heapdiff.cc:236:35: note: candidate is:
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:24: note: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:24: note:   candidate expects 1 argument, 0 provided
../src/heapdiff.cc:239:35: error: no matching function for call to ‘v8::Object::New()’
     Local<Object> b = Object::New();
                                   ^
../src/heapdiff.cc:239:35: note: candidate is:
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:24: note: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:24: note:   candidate expects 1 argument, 0 provided
../src/heapdiff.cc:240:12: error: ‘New’ is not a member of ‘v8::String’
     b->Set(String::New("nodes"), Integer::New(before->GetNodesCount()));
            ^
../src/heapdiff.cc:240:70: error: no matching function for call to ‘v8::Integer::New(int)’
     b->Set(String::New("nodes"), Integer::New(before->GetNodesCount()));
                                                                      ^
../src/heapdiff.cc:240:70: note: candidate is:
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
../src/heapdiff.cc:241:12: error: ‘New’ is not a member of ‘v8::String’
     b->Set(String::New("time"), NODE_UNIXTIME_V8(s_startTime));
            ^
../src/heapdiff.cc:242:12: error: ‘New’ is not a member of ‘v8::String’
     o->Set(String::New("before"), b);
            ^
../src/heapdiff.cc:244:35: error: no matching function for call to ‘v8::Object::New()’
     Local<Object> a = Object::New();
                                   ^
../src/heapdiff.cc:244:35: note: candidate is:
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:24: note: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:24: note:   candidate expects 1 argument, 0 provided
../src/heapdiff.cc:245:12: error: ‘New’ is not a member of ‘v8::String’
     a->Set(String::New("nodes"), Integer::New(after->GetNodesCount()));
            ^
../src/heapdiff.cc:245:69: error: no matching function for call to ‘v8::Integer::New(int)’
     a->Set(String::New("nodes"), Integer::New(after->GetNodesCount()));
                                                                     ^
../src/heapdiff.cc:245:69: note: candidate is:
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
../src/heapdiff.cc:246:12: error: ‘New’ is not a member of ‘v8::String’
     a->Set(String::New("time"), NODE_UNIXTIME_V8(time(NULL)));
            ^
../src/heapdiff.cc:247:12: error: ‘New’ is not a member of ‘v8::String’
     o->Set(String::New("after"), a);
            ^
../src/heapdiff.cc:253:12: error: ‘New’ is not a member of ‘v8::String’
     b->Set(String::New("size_bytes"), Integer::New(s));
            ^
../src/heapdiff.cc:253:53: error: no matching function for call to ‘v8::Integer::New(int&)’
     b->Set(String::New("size_bytes"), Integer::New(s));
                                                     ^
../src/heapdiff.cc:253:53: note: candidate is:
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
../src/heapdiff.cc:254:12: error: ‘New’ is not a member of ‘v8::String’
     b->Set(String::New("size"), String::New(mw_util::niceSize(s).c_str()));
            ^
../src/heapdiff.cc:254:33: error: ‘New’ is not a member of ‘v8::String’
     b->Set(String::New("size"), String::New(mw_util::niceSize(s).c_str()));
                                 ^
../src/heapdiff.cc:259:12: error: ‘New’ is not a member of ‘v8::String’
     a->Set(String::New("size_bytes"), Integer::New(s));
            ^
../src/heapdiff.cc:259:53: error: no matching function for call to ‘v8::Integer::New(int&)’
     a->Set(String::New("size_bytes"), Integer::New(s));
                                                     ^
../src/heapdiff.cc:259:53: note: candidate is:
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
../src/heapdiff.cc:260:12: error: ‘New’ is not a member of ‘v8::String’
     a->Set(String::New("size"), String::New(mw_util::niceSize(s).c_str()));
            ^
../src/heapdiff.cc:260:33: error: ‘New’ is not a member of ‘v8::String’
     a->Set(String::New("size"), String::New(mw_util::niceSize(s).c_str()));
                                 ^
../src/heapdiff.cc:264:35: error: no matching function for call to ‘v8::Object::New()’
     Local<Object> c = Object::New();
                                   ^
../src/heapdiff.cc:264:35: note: candidate is:
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:24: note: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:24: note:   candidate expects 1 argument, 0 provided
../src/heapdiff.cc:265:12: error: ‘New’ is not a member of ‘v8::String’
     c->Set(String::New("size_bytes"), Integer::New(diffBytes));
            ^
../src/heapdiff.cc:265:61: error: no matching function for call to ‘v8::Integer::New(int&)’
     c->Set(String::New("size_bytes"), Integer::New(diffBytes));
                                                             ^
../src/heapdiff.cc:265:61: note: candidate is:
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
../src/heapdiff.cc:266:12: error: ‘New’ is not a member of ‘v8::String’
     c->Set(String::New("size"), String::New(mw_util::niceSize(diffBytes).c_str()));
            ^
../src/heapdiff.cc:266:33: error: ‘New’ is not a member of ‘v8::String’
     c->Set(String::New("size"), String::New(mw_util::niceSize(diffBytes).c_str()));
                                 ^
../src/heapdiff.cc:267:12: error: ‘New’ is not a member of ‘v8::String’
     o->Set(String::New("change"), c);
            ^
../src/heapdiff.cc:272:12: error: ‘New’ is not a member of ‘v8::String’
     c->Set(String::New("freed_nodes"), Integer::New(changedIDs.size()));
            ^
../src/heapdiff.cc:272:70: error: no matching function for call to ‘v8::Integer::New(std::vector<long unsigned int>::size_type)’
     c->Set(String::New("freed_nodes"), Integer::New(changedIDs.size()));
                                                                      ^
../src/heapdiff.cc:272:70: note: candidate is:
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
../src/heapdiff.cc:288:12: error: ‘New’ is not a member of ‘v8::String’
     c->Set(String::New("allocated_nodes"), Integer::New(changedIDs.size()));
            ^
../src/heapdiff.cc:288:74: error: no matching function for call to ‘v8::Integer::New(std::vector<long unsigned int>::size_type)’
     c->Set(String::New("allocated_nodes"), Integer::New(changedIDs.size()));
                                                                          ^
../src/heapdiff.cc:288:74: note: candidate is:
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
../src/heapdiff.cc:295:12: error: ‘New’ is not a member of ‘v8::String’
     c->Set(String::New("details"), changesetToObject(changes));
            ^
../src/heapdiff.cc:297:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(o);
                  ^
../src/heapdiff.cc: At global scope:
../src/heapdiff.cc:301:32: error: ‘Arguments’ does not name a type
 heapdiff::HeapDiff::End( const Arguments& args )
                                ^
In file included from ../src/heapdiff.hh:8:0,
                 from ../src/heapdiff.cc:5:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h: In static member function ‘static v8::Handle<v8::Value> heapdiff::HeapDiff::End(const int&)’:
/home/fat/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/heapdiff.cc:304:21: error: within this context
     v8::HandleScope scope;
                     ^
../src/heapdiff.cc:306:19: error: ‘Unwrap’ was not declared in this scope
     HeapDiff *t = Unwrap<HeapDiff>( args.This() );
                   ^
../src/heapdiff.cc:306:34: error: expected primary-expression before ‘>’ token
     HeapDiff *t = Unwrap<HeapDiff>( args.This() );
                                  ^
../src/heapdiff.cc:306:42: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
     HeapDiff *t = Unwrap<HeapDiff>( args.This() );
                                          ^
../src/heapdiff.cc:312:16: error: ‘ThrowException’ is not a member of ‘v8’
         return v8::ThrowException(
                ^
../src/heapdiff.cc:314:17: error: ‘New’ is not a member of ‘v8::String’
                 v8::String::New("attempt to end() a HeapDiff that was "
                 ^
../src/heapdiff.cc:320:16: error: ‘TakeSnapshot’ is not a member of ‘v8::HeapProfiler’
     t->after = v8::HeapProfiler::TakeSnapshot(v8::String::New(""));
                ^
../src/heapdiff.cc:320:47: error: ‘New’ is not a member of ‘v8::String’
     t->after = v8::HeapProfiler::TakeSnapshot(v8::String::New(""));
                                               ^
../src/heapdiff.cc:331:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(comparison);
                  ^
../src/heapdiff.cc: In static member function ‘static v8::Handle<v8::Value> heapdiff::HeapDiff::New(const int&)’:
../src/heapdiff.cc:86:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/heapdiff.cc: In static member function ‘static v8::Handle<v8::Value> heapdiff::HeapDiff::End(const int&)’:
../src/heapdiff.cc:332:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/heapdiff.cc: In function ‘v8::Handle<v8::Value> compare(const v8::HeapSnapshot*, const v8::HeapSnapshot*)’:
../src/heapdiff.cc:298:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
memwatch.target.mk:86: recipe for target 'Release/obj.target/memwatch/src/heapdiff.o' failed
make: *** [Release/obj.target/memwatch/src/heapdiff.o] Error 1
make: Leaving directory '/home/fat/Projects/Proj/api/node_modules/memwatch/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.19.0-25-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/fat/Projects/Projapi/node_modules/memwatch
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "memwatch"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! memwatch@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the memwatch@0.2.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the memwatch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls memwatch
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fat/Projects/Proj/api/npm-debug.log
```

**Comment by wassimsalib** [comment]
+1 same exact problem like @fatmatto on Ubuntu

**Comment by jckchang** [comment]
+1 same problem with FreeBSD

**Comment by samueleaton** [comment]
Mine was saying `g++ not found` so its possible that there are some missing packages.

**Comment by c0un7-z3r0** [comment]
+1 same issue on centos 6 with gcc 4.9.2 and node 4.4.7

**Comment by iyunusov** [comment]
Is anyone alive here to provide solution, instead of mentioning that you have the same problem?
