### ISSUE TITLE
io.js support?

### ISSUE THREAD

**Issue by cworsley4** [lloyd/node-memwatch#64]
Hello,
I was wondering if there was a plan to support more recent versions of V8 with this package? I am unable to install for io.js 1.4.2 , but node.js 0.10.33 works just fine. Thanks!

**Comment by ralphtheninja** [comment]
_bump_

**Comment by sbrl** [comment]
I get the following error:

```
E:\path>npm install https://github.com/lloyd/node-memwatch.git
npm WARN package.json hull-university-ical@0.0.1 No repository field.
-
> memwatch@0.2.2 install E:\path\node_modules\memwatch
> node-gyp rebuild


E:\path\memwatch>if not defined npm_config_node_gyp (node "C:\Program Files\iojs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
gyp ERR! configure error
gyp ERR! stack Error: spawn python ENOENT
gyp ERR! stack     at exports._errnoException (util.js:749:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:987:32)
gyp ERR! stack     at child_process.js:1079:20
gyp ERR! stack     at process._tickCallback (node.js:340:13)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\iojs\\node.exe" "C:\\Program Files\\iojs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\path\node_modules\memwatch
gyp ERR! node -v v1.7.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\iojs\\node.exe" "C:\\Program Files\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/lloyd/node-memwatch.git"
npm ERR! node v1.7.1
npm ERR! npm  v2.7.6
npm ERR! code ELIFECYCLE

npm ERR! memwatch@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the memwatch@0.2.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the memwatch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls memwatch
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\path\npm-debug.log
```

Paths have been changed for privacy reasons.

**Comment by ChALkeR** [comment]
[memwatch-next](https://github.com/marcominetti/node-memwatch) works, it has all the patches needed.

**Comment by sbrl** [comment]
@ChALkeR Cool, thanks!

So do I install that by typing `npm install https://github.com/marcominetti/node-memwatch.git` then?

**Comment by ChALkeR** [comment]
`npm install memwatch-next` works for me.

**Comment by sbrl** [comment]
Thanks!
I will try out when I get access to a compatible machine.

-------- Original message --------

**Comment by nmccready** [comment]
Where is memwatch-next on github? That project should take over as memwatch appears to be stale / dead.

**Comment by ChALkeR** [comment]
I posted a link above.

**Comment by nmccready** [comment]
my bad ty
