### ISSUE TITLE
unable to install memwatch in window 8.1 and 10

### ISSUE THREAD

**Issue by VenkateshSrini** [lloyd/node-memwatch#66]
Hi,
Installing of memwatch files while installing in windows 8.1 and window 10 results in following error.

0 info it worked if it ends with ok
1 verbose cli [ 'E:\Program Files\nodejs\\node.exe',
1 verbose cli   'E:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'memwatch' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose install initial load of E:\Venkatesh\nodeCode\memwatch\package.json
5 verbose readDependencies loading dependencies from E:\Venkatesh\nodeCode\memwatch\package.json
6 silly cache add args [ 'memwatch', null ]
7 verbose cache add spec memwatch
8 silly cache add parsed spec { raw: 'memwatch',
8 silly cache add   scope: null,
8 silly cache add   name: 'memwatch',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '_',
8 silly cache add   type: 'range' }
9 silly addNamed memwatch@_
10 verbose addNamed "_" is a valid semver range for memwatch
11 silly addNameRange { name: 'memwatch', range: '_', hasData: false }
12 silly mapToRegistry name memwatch
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/memwatch
16 verbose addNameRange registry:https://registry.npmjs.org/memwatch not in flight; fetching
17 verbose request uri https://registry.npmjs.org/memwatch
18 verbose request no auth needed
19 info attempt registry request try #1 at 6:54:33 PM
20 verbose request id a0ad07aaba122ee4
21 http request GET https://registry.npmjs.org/memwatch
22 http 200 https://registry.npmjs.org/memwatch
23 silly get cb [ 200,
23 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly get     etag: '"9CNVDN98D4CJU4Y9831AAILAT"',
23 silly get     'content-type': 'application/json',
23 silly get     'cache-control': 'max-age=60',
23 silly get     'content-length': '37366',
23 silly get     'accept-ranges': 'bytes',
23 silly get     date: 'Sun, 09 Aug 2015 13:24:36 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-sin6920-SIN',
23 silly get     'x-cache': 'MISS',
23 silly get     'x-cache-hits': '0',
23 silly get     'x-timer': 'S1439126676.324669,VS0,VE500',
23 silly get     vary: 'Accept' } ]
24 verbose get saving memwatch to C:\Users\heman\AppData\Roaming\npm-cache\registry.npmjs.org\memwatch.cache.json
25 verbose getCacheStat cache creation not in flight; initializing
26 verbose makeCacheDir UID & GID are irrelevant on win32
27 silly addNameRange number 2 { name: 'memwatch', range: '_', hasData: true }
28 silly addNameRange versions [ 'memwatch',
28 silly addNameRange   [ '0.1.0',
28 silly addNameRange     '0.1.1',
28 silly addNameRange     '0.1.2',
28 silly addNameRange     '0.1.3',
28 silly addNameRange     '0.1.4',
28 silly addNameRange     '0.1.5',
28 silly addNameRange     '0.2.0',
28 silly addNameRange     '0.2.1',
28 silly addNameRange     '0.2.2' ] ]
29 silly addNamed memwatch@0.2.2
30 verbose addNamed "0.2.2" is a plain semver version for memwatch
31 silly mapToRegistry name memwatch
32 silly mapToRegistry using default registry
33 silly mapToRegistry registry https://registry.npmjs.org/
34 silly mapToRegistry uri https://registry.npmjs.org/memwatch
35 verbose addRemoteTarball https://registry.npmjs.org/memwatch/-/memwatch-0.2.2.tgz not in flight; adding
36 verbose addRemoteTarball [ 'https://registry.npmjs.org/memwatch/-/memwatch-0.2.2.tgz',
36 verbose addRemoteTarball   '779e8cd982532b6221b6ed1c1269098bee16f92c' ]
37 info retry fetch attempt 1 at 6:54:34 PM
38 info attempt registry request try #1 at 6:54:34 PM
39 http fetch GET https://registry.npmjs.org/memwatch/-/memwatch-0.2.2.tgz
40 http fetch 200 https://registry.npmjs.org/memwatch/-/memwatch-0.2.2.tgz
41 silly fetchAndShaCheck shasum 779e8cd982532b6221b6ed1c1269098bee16f92c
42 verbose addTmpTarball C:\Users\heman\AppData\Local\Temp\npm-4340-96eeeb15\registry.npmjs.org\memwatch-\memwatch-0.2.2.tgz not in flight; adding
43 verbose addTmpTarball already have metadata; skipping unpack for memwatch@0.2.2
44 silly cache afterAdd memwatch@0.2.2
45 verbose afterAdd C:\Users\heman\AppData\Roaming\npm-cache\memwatch\0.2.2\package\package.json not in flight; writing
46 verbose afterAdd C:\Users\heman\AppData\Roaming\npm-cache\memwatch\0.2.2\package\package.json written
47 silly install resolved [ { name: 'memwatch',
47 silly install resolved     description: 'Keep an eye on your memory usage, and discover and isolate leaks.',
47 silly install resolved     version: '0.2.2',
47 silly install resolved     author: { name: 'Lloyd Hilaiel', url: 'http://lloyd.io' },
47 silly install resolved     engines: { node: '>= 0.6.0' },
47 silly install resolved     repository:
47 silly install resolved      { type: 'git',
47 silly install resolved        url: 'https://github.com/lloyd/node-memwatch.git' },
47 silly install resolved     main: 'include.js',
47 silly install resolved     licenses: [ [Object] ],
47 silly install resolved     bugs: { url: 'https://github.com/lloyd/node-memwatch/issues' },
47 silly install resolved     scripts: { install: 'node-gyp rebuild', test: 'mocha tests' },
47 silly install resolved     devDependencies: { mocha: '1.2.2', should: '0.6.3', 'node-gyp': '0.5.7' },
47 silly install resolved     contributors: [ [Object], [Object], [Object] ],
47 silly install resolved     readme: '`node-memwatch`: Leak Detection and Heap Diffing for Node.JS\n============================================================\n\n[![Build Status](https://secure.travis-ci.org/lloyd/node-memwatch.png)](http://travis-ci.org/lloyd/node-memwatch)\n\n`node-memwatch` is here to help you detect and find memory leaks in\nNode.JS code.  It provides:\n\n- A `leak` event, emitted when it appears your code is leaking memory.\n\n- A `stats` event, emitted occasionally, giving you\n  data describing your heap usage and trends over time.\n\n- A `HeapDiff` class that lets you compare the state of your heap between\n  two points in time, telling you what has been allocated, and what\n  has been released.\n\n\nInstallation\n------------\n\n- `npm install memwatch`\n\nor\n\n- `git clone git://github.com/lloyd/node-memwatch.git`\n\n\nDescription\n-----------\n\nThere are a growing number of tools for debugging and profiling memory\nusage in Node.JS applications, but there is still a need for a\nplatform-independent native module that requires no special\ninstrumentation.  This module attempts to satisfy that need.\n\nTo get started, import `node-memwatch` like so:\n\n`javascript\nvar memwatch = require(\'memwatch\');\n`\n\n### Leak Detection\n\nYou can then subscribe to `leak` events.  A `leak` event will be\nemitted when your heap usage has increased for five consecutive\ngarbage collections:\n\n`javascript\nmemwatch.on(\'leak\', function(info) { ... });\n`\n\nThe `info` object will look something like:\n\n`javascript\n{ start: Fri, 29 Jun 2012 14:12:13 GMT,\n  end: Fri, 29 Jun 2012 14:12:33 GMT,\n  growth: 67984,\n  reason: \'heap growth over 5 consecutive GCs (20s) - 11.67 mb/hr\' }\n`\n\n\n### Heap Usage\n\nThe best way to evaluate your memory footprint is to look at heap\nusage right aver V8 performs garbage collection.  `memwatch` does\nexactly this - it checks heap usage only after GC to give you a stable\nbaseline of your actual memory usage.\n\nWhen V8 performs a garbage collection (technically, we\'re talking\nabout a full GC with heap compaction), `memwatch` will emit a `stats`\nevent.\n\n`javascript\nmemwatch.on(\'stats\', function(stats) { ... });\n`\n\nThe `stats` data will look something like this:\n\n`javascript\n{\n  "num_full_gc": 17,\n  "num_inc_gc": 8,\n  "heap_compactions": 8,\n  "estimated_base": 2592568,\n  "current_base": 2592568,\n  "min": 2499912,\n  "max": 2592568,\n  "usage_trend": 0\n}\n`\n\n`estimated_base` and `usage_trend` are tracked over time.  If usage\ntrend is consistently positive, it indicates that your base heap size\nis continuously growing and you might have a leak.\n\nV8 has its own idea of when it\'s best to perform a GC, and under a\nheavy load, it may defer this action for some time.  To aid in\nspeedier debugging, `memwatch` provides a `gc()` method to force V8 to\ndo a full GC and heap compaction.\n\n\n### Heap Diffing\n\nSo far we have seen how `memwatch` can aid in leak detection.  For\nleak isolation, it provides a `HeapDiff` class that takes two snapshots\nand computes a diff between them.  For example:\n\n`javascript\n// Take first snapshot\nvar hd = new memwatch.HeapDiff();\n\n// do some things ...\n\n// Take the second snapshot and compute the diff\nvar diff = hd.end();\n`\n\nThe contents of `diff` will look something like:\n\n`javascript\n{\n  "before": { "nodes": 11625, "size_bytes": 1869904, "size": "1.78 mb" },\n  "after":  { "nodes": 21435, "size_bytes": 2119136, "size": "2.02 mb" },\n  "change": { "size_bytes": 249232, "size": "243.39 kb", "freed_nodes": 197,\n    "allocated_nodes": 10007,\n    "details": [\n      { "what": "String",\n        "size_bytes": -2120,  "size": "-2.07 kb",  "+": 3,    "-": 62\n      },\n      { "what": "Array",\n        "size_bytes": 66687,  "size": "65.13 kb",  "+": 4,    "-": 78\n      },\n      { "what": "LeakingClass",\n        "size_bytes": 239952, "size": "234.33 kb", "+": 9998, "-": 0\n      }\n    ]\n  }\n`\n\nThe diff shows that during the sample period, the total number of\nallocated `String` and `Array` classes decreased, but `Leaking Class`\ngrew by 9998 allocations.  Hmmm.\n\nYou can use `HeapDiff` in your `on(\'stats\')` callback; even though it\ntakes a memory snapshot, which triggers a V8 GC, it will not trigger\nthe `stats` event itself.  Because that would be silly.\n\n\nFuture Work\n-----------\n\nPlease see the Issues to share suggestions and contribute!\n\n\nLicense\n-------\n\nhttp://wtfpl.org\n',
47 silly install resolved     readmeFilename: 'README.md',
47 silly install resolved     _id: 'memwatch@0.2.2',
47 silly install resolved     dist:
47 silly install resolved      { shasum: '779e8cd982532b6221b6ed1c1269098bee16f92c',
47 silly install resolved        tarball: 'http://registry.npmjs.org/memwatch/-/memwatch-0.2.2.tgz' },
47 silly install resolved     _from: 'memwatch@_',
47 silly install resolved     _npmVersion: '1.2.14',
47 silly install resolved     _npmUser: { name: 'lloyd', email: 'lloyd@hilaiel.com' },
47 silly install resolved     maintainers: [ [Object] ],
47 silly install resolved     directories: {},
47 silly install resolved     _shasum: '779e8cd982532b6221b6ed1c1269098bee16f92c',
47 silly install resolved     _resolved: 'https://registry.npmjs.org/memwatch/-/memwatch-0.2.2.tgz' } ]
48 info install memwatch@0.2.2 into E:\Venkatesh\nodeCode\memwatch
49 info installOne memwatch@0.2.2
50 verbose installOne of memwatch to E:\Venkatesh\nodeCode\memwatch not in flight; installing
51 verbose lock using C:\Users\heman\AppData\Roaming\npm-cache_locks\memwatch-0bffd97e44cc91cf.lock for E:\Venkatesh\nodeCode\memwatch\node_modules\memwatch
52 silly install write writing memwatch 0.2.2 to E:\Venkatesh\nodeCode\memwatch\node_modules\memwatch
53 verbose unbuild node_modules\memwatch
54 silly gentlyRm E:\Venkatesh\nodeCode\memwatch\node_modules\memwatch is being purged from base E:\Venkatesh\nodeCode\memwatch
55 verbose gentlyRm don't care about contents; nuking E:\Venkatesh\nodeCode\memwatch\node_modules\memwatch
56 verbose tar unpack C:\Users\heman\AppData\Roaming\npm-cache\memwatch\0.2.2\package.tgz
57 verbose tar unpacking to E:\Venkatesh\nodeCode\memwatch\node_modules\memwatch
58 silly gentlyRm E:\Venkatesh\nodeCode\memwatch\node_modules\memwatch is being purged
59 verbose gentlyRm don't care about contents; nuking E:\Venkatesh\nodeCode\memwatch\node_modules\memwatch
60 silly gunzTarPerm modes [ '777', '666' ]
61 silly gunzTarPerm extractEntry package.json
62 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
63 silly gunzTarPerm extractEntry .npmignore
64 silly gunzTarPerm modified mode [ '.npmignore', 420, 438 ]
65 silly gunzTarPerm extractEntry README.md
66 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
67 silly gunzTarPerm extractEntry tests.js
68 silly gunzTarPerm modified mode [ 'tests.js', 420, 438 ]
69 silly gunzTarPerm extractEntry foo.js
70 silly gunzTarPerm modified mode [ 'foo.js', 420, 438 ]
71 silly gunzTarPerm extractEntry include.js
72 silly gunzTarPerm modified mode [ 'include.js', 420, 438 ]
73 silly gunzTarPerm extractEntry .travis.yml
74 silly gunzTarPerm modified mode [ '.travis.yml', 420, 438 ]
75 silly gunzTarPerm extractEntry ChangeLog
76 silly gunzTarPerm modified mode [ 'ChangeLog', 420, 438 ]
77 silly gunzTarPerm extractEntry #wscript#
78 silly gunzTarPerm modified mode [ '#wscript#', 420, 438 ]
79 silly gunzTarPerm extractEntry binding.gyp
80 silly gunzTarPerm modified mode [ 'binding.gyp', 420, 438 ]
81 silly gunzTarPerm extractEntry src/heapdiff.cc
82 silly gunzTarPerm modified mode [ 'src/heapdiff.cc', 420, 438 ]
83 silly gunzTarPerm extractEntry src/heapdiff.hh
84 silly gunzTarPerm modified mode [ 'src/heapdiff.hh', 420, 438 ]
85 silly gunzTarPerm extractEntry src/init.cc
86 silly gunzTarPerm modified mode [ 'src/init.cc', 420, 438 ]
87 silly gunzTarPerm extractEntry src/memwatch.cc
88 silly gunzTarPerm modified mode [ 'src/memwatch.cc', 420, 438 ]
89 silly gunzTarPerm extractEntry src/memwatch.hh
90 silly gunzTarPerm modified mode [ 'src/memwatch.hh', 420, 438 ]
91 silly gunzTarPerm extractEntry src/platformcompat.hh
92 silly gunzTarPerm modified mode [ 'src/platformcompat.hh', 420, 438 ]
93 silly gunzTarPerm extractEntry src/util.cc
94 silly gunzTarPerm modified mode [ 'src/util.cc', 420, 438 ]
95 silly gunzTarPerm extractEntry src/util.hh
96 silly gunzTarPerm modified mode [ 'src/util.hh', 420, 438 ]
97 silly gunzTarPerm extractEntry examples/basic_heapdiff.js
98 silly gunzTarPerm modified mode [ 'examples/basic_heapdiff.js', 420, 438 ]
99 silly gunzTarPerm extractEntry examples/do_nothing_server.js
100 silly gunzTarPerm modified mode [ 'examples/do_nothing_server.js', 420, 438 ]
101 silly gunzTarPerm extractEntry examples/slightly_leaky.js
102 silly gunzTarPerm modified mode [ 'examples/slightly_leaky.js', 420, 438 ]
103 verbose write writing to E:\Venkatesh\nodeCode\memwatch\node_modules\memwatch\package.json
104 info preinstall memwatch@0.2.2
105 verbose readDependencies loading dependencies from E:\Venkatesh\nodeCode\memwatch\node_modules\memwatch\package.json
106 verbose readDependencies loading dependencies from E:\Venkatesh\nodeCode\memwatch\node_modules\memwatch\package.json
107 silly install resolved []
108 verbose about to build E:\Venkatesh\nodeCode\memwatch\node_modules\memwatch
109 info build E:\Venkatesh\nodeCode\memwatch\node_modules\memwatch
110 info linkStuff memwatch@0.2.2
111 silly linkStuff memwatch@0.2.2 has E:\Venkatesh\nodeCode\memwatch\node_modules as its parent node_modules
112 verbose linkBins memwatch@0.2.2
113 verbose linkMans memwatch@0.2.2
114 verbose rebuildBundles memwatch@0.2.2
115 info install memwatch@0.2.2
116 verbose unsafe-perm in lifecycle true
117 info memwatch@0.2.2 Failed to exec install script
118 verbose unlock done using C:\Users\heman\AppData\Roaming\npm-cache_locks\memwatch-0bffd97e44cc91cf.lock for E:\Venkatesh\nodeCode\memwatch\node_modules\memwatch
119 verbose stack Error: memwatch@0.2.2 install: `node-gyp rebuild`
119 verbose stack Exit status 1
119 verbose stack     at EventEmitter.<anonymous> (E:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
119 verbose stack     at EventEmitter.emit (events.js:110:17)
119 verbose stack     at ChildProcess.<anonymous> (E:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
119 verbose stack     at ChildProcess.emit (events.js:110:17)
119 verbose stack     at maybeClose (child_process.js:1015:16)
119 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
120 verbose pkgid memwatch@0.2.2
121 verbose cwd E:\Venkatesh\nodeCode\memwatch
122 error Windows_NT 6.3.9600
123 error argv "E:\Program Files\nodejs\\node.exe" "E:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "memwatch"
124 error node v0.12.7
125 error npm  v2.11.3
126 error code ELIFECYCLE
127 error memwatch@0.2.2 install: `node-gyp rebuild`
127 error Exit status 1
128 error Failed at the memwatch@0.2.2 install script 'node-gyp rebuild'.
128 error This is most likely a problem with the memwatch package,
128 error not with npm itself.
128 error Tell the author that this fails on your system:
128 error     node-gyp rebuild
128 error You can get their info via:
128 error     npm owner ls memwatch
128 error There is likely additional logging output above.
129 verbose exit [ 1, true ]
130 verbose unbuild node_modules\memwatch
131 info preuninstall memwatch@0.2.2
132 info uninstall memwatch@0.2.2
133 verbose unbuild rmStuff memwatch@0.2.2 from E:\Venkatesh\nodeCode\memwatch\node_modules
134 info postuninstall memwatch@0.2.2
135 silly gentlyRm E:\Venkatesh\nodeCode\memwatch\node_modules\memwatch is being purged from base E:\Venkatesh\nodeCode\memwatch
136 verbose gentlyRm don't care about contents; nuking E:\Venkatesh\nodeCode\memwatch\node_modules\memwatch
137 silly vacuum-fs purging E:\Venkatesh\nodeCode\memwatch\node_modules\memwatch
138 silly vacuum-fs removing E:\Venkatesh\nodeCode\memwatch\node_modules
139 silly vacuum-fs finished vacuuming up to E:\Venkatesh\nodeCode\memwatch

Please help  us in this regard
Regards 
Venkatesh

**Comment by EricSmekens** [comment]
Does not support on node.js v.0.12 #62
