### ISSUE TITLE
OSX install fails

### ISSUE THREAD

**Issue by chisleu** [lloyd/node-memwatch#68]
I installed xcode and agreed to the license, which removed some errors, but now it makes even more errors

Here goes:

```
|
> memwatch@0.2.2 install /Users/USERNAME/PATH/PATH/node_modules/memwatch
> node-gyp rebuild

  CXX(target) Release/obj.target/memwatch/src/heapdiff.o
In file included from ../src/heapdiff.cc:5:
../src/heapdiff.hh:14:35: error: expected class name
    class HeapDiff : public node::ObjectWrap
                                  ^
../src/heapdiff.hh:19:49: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> New( const v8::Arguments& args );
                                                ^~~~~~~~~~~~~
                                                v8::internal::Arguments
/Users/USERNAME/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/heapdiff.cc:5:
../src/heapdiff.hh:20:49: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> End( const v8::Arguments& args );
                                                ^~~~~~~~~~~~~
                                                v8::internal::Arguments
/Users/USERNAME/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/heapdiff.cc:30:34: error: member initializer 'ObjectWrap' does not name a non-static data member or base class
heapdiff::HeapDiff::HeapDiff() : ObjectWrap(), before(NULL), after(NULL),
                                 ^~~~~~~~~~~~
../src/heapdiff.cc:51:21: error: calling a protected constructor of class 'v8::HandleScope'
    v8::HandleScope scope;
                    ^
/Users/USERNAME/.node-gyp/0.12.7/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/heapdiff.cc:52:67: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type
      'v8::Handle<v8::Value> (const v8::internal::Arguments &)'
    v8::Local<v8::FunctionTemplate> t = v8::FunctionTemplate::New(New);
                                                                  ^~~
/Users/USERNAME/.node-gyp/0.12.7/deps/v8/include/v8.h:3456:16: note: passing argument to parameter 'isolate' here
      Isolate* isolate,
               ^
../src/heapdiff.cc:54:29: error: no member named 'NewSymbol' in 'v8::String'
    t->SetClassName(String::NewSymbol("HeapDiff"));
                    ~~~~~~~~^
../src/heapdiff.cc:56:41: error: cannot initialize a parameter of type 'v8::FunctionCallback' (aka 'void (*)(const
      FunctionCallbackInfo<v8::Value> &)') with an lvalue of type 'v8::Handle<v8::Value>
      (const v8::internal::Arguments &)': type mismatch at 1st parameter ('const FunctionCallbackInfo<v8::Value> &'
      vs 'const v8::internal::Arguments &')
    NODE_SET_PROTOTYPE_METHOD(t, "end", End);
                                        ^~~
/Users/USERNAME/.node-gyp/0.12.7/src/node.h:246:60: note: passing argument to parameter 'callback' here
                                      v8::FunctionCallback callback) {
                                                           ^
../src/heapdiff.cc:58:29: error: no member named 'NewSymbol' in 'v8::String'
    target->Set(v8::String::NewSymbol( "HeapDiff"), t->GetFunction());
                ~~~~~~~~~~~~^
../src/heapdiff.cc:62:32: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
heapdiff::HeapDiff::New (const v8::Arguments& args)
                               ^~~~~~~~~~~~~
                               v8::internal::Arguments
/Users/USERNAME/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/heapdiff.cc:67:14: error: member access into incomplete type 'const v8::internal::Arguments'
    if (!args.IsConstructCall()) {
             ^
/Users/USERNAME/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/heapdiff.cc:70:17: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
                String::New("Use the new operator to create instances of this object.")));
                ^~~~~~~~~~~
                New
../src/heapdiff.cc:62:21: note: 'New' declared here
heapdiff::HeapDiff::New (const v8::Arguments& args)
                    ^
../src/heapdiff.cc:70:29: error: reference to type 'const v8::internal::Arguments' could not bind to an lvalue of
      type 'const char [57]'
                String::New("Use the new operator to create instances of this object.")));
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/heapdiff.cc:62:47: note: passing argument to parameter 'args' here
heapdiff::HeapDiff::New (const v8::Arguments& args)
                                              ^
../src/heapdiff.cc:73:21: error: calling a protected constructor of class 'v8::HandleScope'
    v8::HandleScope scope;
                    ^
/Users/USERNAME/.node-gyp/0.12.7/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/heapdiff.cc:77:11: error: no member named 'Wrap' in 'heapdiff::HeapDiff'
    self->Wrap(args.This());
    ~~~~  ^
../src/heapdiff.cc:77:20: error: member access into incomplete type 'const v8::internal::Arguments'
    self->Wrap(args.This());
                   ^
/Users/USERNAME/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/heapdiff.cc:82:38: error: no member named 'TakeSnapshot' in 'v8::HeapProfiler'
    self->before = v8::HeapProfiler::TakeSnapshot(v8::String::New(""));
                   ~~~~~~~~~~~~~~~~~~^
../src/heapdiff.cc:82:51: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
    self->before = v8::HeapProfiler::TakeSnapshot(v8::String::New(""));
                                                  ^~~~~~~~~~~~~~~
                                                  New
../src/heapdiff.cc:62:21: note: 'New' declared here
heapdiff::HeapDiff::New (const v8::Arguments& args)
                    ^
../src/heapdiff.cc:82:67: error: reference to type 'const v8::internal::Arguments' could not bind to an lvalue of
      type 'const char [1]'
    self->before = v8::HeapProfiler::TakeSnapshot(v8::String::New(""));
                                                                  ^~
../src/heapdiff.cc:62:47: note: passing argument to parameter 'args' here
heapdiff::HeapDiff::New (const v8::Arguments& args)
                                              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/memwatch/src/heapdiff.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/USERNAME/PATH/PATH/node_modules/memwatch
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "memwatch"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! memwatch@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the memwatch@0.2.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the memwatch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls memwatch
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/USERNAME/PATH/PATH/npm-debug.log
```

Here is the npm-debug.log that it said I should include:

``````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'memwatch' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose node symlink /usr/local/bin/node
5 verbose install initial load of /Users/USERNAME/PATH/PATH/package.json
6 warn package.json PACKAGENAME@1.0.0 No description
7 warn package.json PACKAGENAME@1.0.0 No repository field.
8 warn package.json PACKAGENAME@1.0.0 No README data
9 warn package.json PACKAGENAME@1.0.0 license should be a valid SPDX license expression
10 verbose installManyTop reading scoped package data from /Users/USERNAME/PATH/PATH/node_modules/async/package.json
11 verbose installManyTop reading scoped package data from /Users/USERNAME/PATH/PATH/node_modules/aws-sdk/package.json
12 verbose installManyTop reading scoped package data from /Users/USERNAME/PATH/PATH/node_modules/bcrypt/package.json
13 verbose installManyTop reading scoped package data from /Users/USERNAME/PATH/PATH/node_modules/body-parser/package.json
14 verbose installManyTop reading scoped package data from /Users/USERNAME/PATH/PATH/node_modules/connect-redis/package.json
15 verbose installManyTop reading scoped package data from /Users/USERNAME/PATH/PATH/node_modules/cookie-parser/package.json
16 verbose installManyTop reading scoped package data from /Users/USERNAME/PATH/PATH/node_modules/debug/package.json
17 verbose installManyTop reading scoped package data from /Users/USERNAME/PATH/PATH/node_modules/escape-html/package.json
18 verbose installManyTop reading scoped package data from /Users/USERNAME/PATH/PATH/node_modules/PATH/package.json
19 verbose installManyTop reading scoped package data from /Users/USERNAME/PATH/PATH/node_modules/PATH-session/package.json
20 verbose installManyTop reading scoped package data from /Users/USERNAME/PATH/PATH/node_modules/gm/package.json
21 verbose installManyTop reading scoped package data from /Users/USERNAME/PATH/PATH/node_modules/jade/package.json
22 verbose installManyTop reading scoped package data from /Users/USERNAME/PATH/PATH/node_modules/less-middleware/package.json
23 verbose installManyTop reading scoped package data from /Users/USERNAME/PATH/PATH/node_modules/moment/package.json
24 verbose installManyTop reading scoped package data from /Users/USERNAME/PATH/PATH/node_modules/morgan/package.json
25 verbose installManyTop reading scoped package data from /Users/USERNAME/PATH/PATH/node_modules/redis/package.json
26 verbose installManyTop reading scoped package data from /Users/USERNAME/PATH/PATH/node_modules/request/package.json
27 verbose installManyTop reading scoped package data from /Users/USERNAME/PATH/PATH/node_modules/serve-favicon/package.json
28 verbose installManyTop reading scoped package data from /Users/USERNAME/PATH/PATH/node_modules/socket.io/package.json
29 verbose installManyTop reading scoped package data from /Users/USERNAME/PATH/PATH/node_modules/timezoner/package.json
30 verbose installManyTop reading scoped package data from /Users/USERNAME/PATH/PATH/node_modules/uuid/package.json
31 verbose installManyTop reading scoped package data from /Users/USERNAME/PATH/PATH/node_modules/validator/package.json
32 info package.json less-middleware@2.0.1 No license field.
33 info package.json redis@0.12.1 No license field.
34 info package.json socket.io@1.3.6 No license field.
35 info package.json timezoner@0.1.9 No license field.
36 info package.json uuid@2.0.1 No license field.
37 verbose readDependencies loading dependencies from /Users/USERNAME/PATH/PATH/package.json
38 silly cache add args [ 'memwatch@^0.2.2', null ]
39 verbose cache add spec memwatch@^0.2.2
40 silly cache add parsed spec { raw: 'memwatch@^0.2.2',
40 silly cache add   scope: null,
40 silly cache add   name: 'memwatch',
40 silly cache add   rawSpec: '^0.2.2',
40 silly cache add   spec: '>=0.2.2 <0.3.0',
40 silly cache add   type: 'range' }
41 silly addNamed memwatch@>=0.2.2 <0.3.0
42 verbose addNamed ">=0.2.2 <0.3.0" is a valid semver range for memwatch
43 silly addNameRange { name: 'memwatch', range: '>=0.2.2 <0.3.0', hasData: false }
44 silly mapToRegistry name memwatch
45 silly mapToRegistry using default registry
46 silly mapToRegistry registry https://registry.npmjs.org/
47 silly mapToRegistry uri https://registry.npmjs.org/memwatch
48 verbose addNameRange registry:https://registry.npmjs.org/memwatch not in flight; fetching
49 verbose request uri https://registry.npmjs.org/memwatch
50 verbose request no auth needed
51 info attempt registry request try #1 at 4:10:18 AM
52 verbose request id 12de2af56c333531
53 verbose etag "1F29AGC6QNBGKFZQR3ZUK4J81"
54 http request GET https://registry.npmjs.org/memwatch
55 http 304 https://registry.npmjs.org/memwatch
56 silly get cb [ 304,
56 silly get   { date: 'Tue, 01 Sep 2015 08:10:18 GMT',
56 silly get     via: '1.1 varnish',
56 silly get     'cache-control': 'max-age=60',
56 silly get     etag: '"1F29AGC6QNBGKFZQR3ZUK4J81"',
56 silly get     age: '0',
56 silly get     connection: 'keep-alive',
56 silly get     'x-served-by': 'cache-atl6230-ATL',
56 silly get     'x-cache': 'HIT',
56 silly get     'x-cache-hits': '1',
56 silly get     'x-timer': 'S1441095018.888660,VS0,VE86',
56 silly get     vary: 'Accept' } ]
57 verbose etag https://registry.npmjs.org/memwatch from cache
58 verbose get saving memwatch to /Users/USERNAME/.npm/registry.npmjs.org/memwatch/.cache.json
59 silly addNameRange number 2 { name: 'memwatch', range: '>=0.2.2 <0.3.0', hasData: true }
60 silly addNameRange versions [ 'memwatch',
60 silly addNameRange   [ '0.1.0',
60 silly addNameRange     '0.1.1',
60 silly addNameRange     '0.1.2',
60 silly addNameRange     '0.1.3',
60 silly addNameRange     '0.1.4',
60 silly addNameRange     '0.1.5',
60 silly addNameRange     '0.2.0',
60 silly addNameRange     '0.2.1',
60 silly addNameRange     '0.2.2' ] ]
61 silly addNamed memwatch@0.2.2
62 verbose addNamed "0.2.2" is a plain semver version for memwatch
63 silly cache afterAdd memwatch@0.2.2
64 verbose afterAdd /Users/USERNAME/.npm/memwatch/0.2.2/package/package.json not in flight; writing
65 verbose afterAdd /Users/USERNAME/.npm/memwatch/0.2.2/package/package.json written
66 silly install resolved [ { name: 'memwatch',
66 silly install resolved     description: 'Keep an eye on your memory usage, and discover and isolate leaks.',
66 silly install resolved     version: '0.2.2',
66 silly install resolved     author: { name: 'Lloyd Hilaiel', url: 'http://lloyd.io' },
66 silly install resolved     engines: { node: '>= 0.6.0' },
66 silly install resolved     repository:
66 silly install resolved      { type: 'git',
66 silly install resolved        url: 'git+https://github.com/lloyd/node-memwatch.git' },
66 silly install resolved     main: 'include.js',
66 silly install resolved     licenses: [ [Object] ],
66 silly install resolved     bugs: { url: 'https://github.com/lloyd/node-memwatch/issues' },
66 silly install resolved     scripts: { install: 'node-gyp rebuild', test: 'mocha tests' },
66 silly install resolved     devDependencies: { mocha: '1.2.2', should: '0.6.3', 'node-gyp': '0.5.7' },
66 silly install resolved     contributors: [ [Object], [Object], [Object] ],
66 silly install resolved     readme: '`node-memwatch`: Leak Detection and Heap Diffing for Node.JS\n============================================================\n\n[![Build Status](https://secure.travis-ci.org/lloyd/node-memwatch.png)](http://travis-ci.org/lloyd/node-memwatch)\n\n`node-memwatch` is here to help you detect and find memory leaks in\nNode.JS code.  It provides:\n\n- A `leak` event, emitted when it appears your code is leaking memory.\n\n- A `stats` event, emitted occasionally, giving you\n  data describing your heap usage and trends over time.\n\n- A `HeapDiff` class that lets you compare the state of your heap between\n  two points in time, telling you what has been allocated, and what\n  has been released.\n\n\nInstallation\n------------\n\n- `npm install memwatch`\n\nor\n\n- `git clone git://github.com/lloyd/node-memwatch.git`\n\n\nDescription\n-----------\n\nThere are a growing number of tools for debugging and profiling memory\nusage in Node.JS applications, but there is still a need for a\nplatform-independent native module that requires no special\ninstrumentation.  This module attempts to satisfy that need.\n\nTo get started, import `node-memwatch` like so:\n\n```javascript\nvar memwatch = require(\'memwatch\');\n```\n\n### Leak Detection\n\nYou can then subscribe to `leak` events.  A `leak` event will be\nemitted when your heap usage has increased for five consecutive\ngarbage collections:\n\n```javascript\nmemwatch.on(\'leak\', function(info) { ... });\n```\n\nThe `info` object will look something like:\n\n```javascript\n{ start: Fri, 29 Jun 2012 14:12:13 GMT,\n  end: Fri, 29 Jun 2012 14:12:33 GMT,\n  growth: 67984,\n  reason: \'heap growth over 5 consecutive GCs (20s) - 11.67 mb/hr\' }\n```\n\n\n### Heap Usage\n\nThe best way to evaluate your memory footprint is to look at heap\nusage right aver V8 performs garbage collection.  `memwatch` does\nexactly this - it checks heap usage only after GC to give you a stable\nbaseline of your actual memory usage.\n\nWhen V8 performs a garbage collection (technically, we\'re talking\nabout a full GC with heap compaction), `memwatch` will emit a `stats`\nevent.\n\n```javascript\nmemwatch.on(\'stats\', function(stats) { ... });\n```\n\nThe `stats` data will look something like this:\n\n```javascript\n{\n  "num_full_gc": 17,\n  "num_inc_gc": 8,\n  "heap_compactions": 8,\n  "estimated_base": 2592568,\n  "current_base": 2592568,\n  "min": 2499912,\n  "max": 2592568,\n  "usage_trend": 0\n}\n```\n\n`estimated_base` and `usage_trend` are tracked over time.  If usage\ntrend is consistently positive, it indicates that your base heap size\nis continuously growing and you might have a leak.\n\nV8 has its own idea of when it\'s best to perform a GC, and under a\nheavy load, it may defer this action for some time.  To aid in\nspeedier debugging, `memwatch` provides a `gc()` method to force V8 to\ndo a full GC and heap compaction.\n\n\n### Heap Diffing\n\nSo far we have seen how `memwatch` can aid in leak detection.  For\nleak isolation, it provides a `HeapDiff` class that takes two snapshots\nand computes a diff between them.  For example:\n\n```javascript\n// Take first snapshot\nvar hd = new memwatch.HeapDiff();\n\n// do some things ...\n\n// Take the second snapshot and compute the diff\nvar diff = hd.end();\n```\n\nThe contents of `diff` will look something like:\n\n```javascript\n{\n  "before": { "nodes": 11625, "size_bytes": 1869904, "size": "1.78 mb" },\n  "after":  { "nodes": 21435, "size_bytes": 2119136, "size": "2.02 mb" },\n  "change": { "size_bytes": 249232, "size": "243.39 kb", "freed_nodes": 197,\n    "allocated_nodes": 10007,\n    "details": [\n      { "what": "String",\n        "size_bytes": -2120,  "size": "-2.07 kb",  "+": 3,    "-": 62\n      },\n      { "what": "Array",\n        "size_bytes": 66687,  "size": "65.13 kb",  "+": 4,    "-": 78\n      },\n      { "what": "LeakingClass",\n        "size_bytes": 239952, "size": "234.33 kb", "+": 9998, "-": 0\n      }\n    ]\n  }\n```\n\nThe diff shows that during the sample period, the total number of\nallocated `String` and `Array` classes decreased, but `Leaking Class`\ngrew by 9998 allocations.  Hmmm.\n\nYou can use `HeapDiff` in your `on(\'stats\')` callback; even though it\ntakes a memory snapshot, which triggers a V8 GC, it will not trigger\nthe `stats` event itself.  Because that would be silly.\n\n\nFuture Work\n-----------\n\nPlease see the Issues to share suggestions and contribute!\n\n\nLicense\n-------\n\nhttp://wtfpl.org\n',
66 silly install resolved     readmeFilename: 'README.md',
66 silly install resolved     _id: 'memwatch@0.2.2',
66 silly install resolved     dist:
66 silly install resolved      { shasum: '779e8cd982532b6221b6ed1c1269098bee16f92c',
66 silly install resolved        tarball: 'http://registry.npmjs.org/memwatch/-/memwatch-0.2.2.tgz' },
66 silly install resolved     _from: 'memwatch@>=0.2.2 <0.3.0',
66 silly install resolved     _npmVersion: '1.2.14',
66 silly install resolved     _npmUser: { name: 'lloyd', email: 'lloyd@hilaiel.com' },
66 silly install resolved     maintainers: [ [Object] ],
66 silly install resolved     directories: {},
66 silly install resolved     _shasum: '779e8cd982532b6221b6ed1c1269098bee16f92c',
66 silly install resolved     _resolved: 'https://registry.npmjs.org/memwatch/-/memwatch-0.2.2.tgz',
66 silly install resolved     gypfile: true,
66 silly install resolved     homepage: 'https://github.com/lloyd/node-memwatch#readme' } ]
67 info install memwatch@0.2.2 into /Users/USERNAME/PATH/PATH
68 info installOne memwatch@0.2.2
69 verbose installOne of memwatch to /Users/USERNAME/PATH/PATH not in flight; installing
70 verbose lock using /Users/USERNAME/.npm/_locks/memwatch-880cc2a1e8439e30.lock for /Users/USERNAME/PATH/PATH/node_modules/memwatch
71 silly install write writing memwatch 0.2.2 to /Users/USERNAME/PATH/PATH/node_modules/memwatch
72 verbose unbuild node_modules/memwatch
73 silly gentlyRm /Users/USERNAME/PATH/PATH/node_modules/memwatch is being purged from base /Users/USERNAME/PATH/PATH
74 verbose gentlyRm don't care about contents; nuking /Users/USERNAME/PATH/PATH/node_modules/memwatch
75 verbose tar unpack /Users/USERNAME/.npm/memwatch/0.2.2/package.tgz
76 verbose tar unpacking to /Users/USERNAME/PATH/PATH/node_modules/memwatch
77 silly gentlyRm /Users/USERNAME/PATH/PATH/node_modules/memwatch is being purged
78 verbose gentlyRm don't care about contents; nuking /Users/USERNAME/PATH/PATH/node_modules/memwatch
79 silly gunzTarPerm modes [ '755', '644' ]
80 silly gunzTarPerm extractEntry package.json
81 silly gunzTarPerm extractEntry .npmignore
82 silly gunzTarPerm extractEntry README.md
83 silly gunzTarPerm extractEntry tests.js
84 silly gunzTarPerm extractEntry foo.js
85 silly gunzTarPerm extractEntry include.js
86 silly gunzTarPerm extractEntry .travis.yml
87 silly gunzTarPerm extractEntry ChangeLog
88 silly gunzTarPerm extractEntry #wscript#
89 silly gunzTarPerm extractEntry binding.gyp
90 silly gunzTarPerm extractEntry src/heapdiff.cc
91 silly gunzTarPerm extractEntry src/heapdiff.hh
92 silly gunzTarPerm extractEntry src/init.cc
93 silly gunzTarPerm extractEntry src/memwatch.cc
94 silly gunzTarPerm extractEntry src/memwatch.hh
95 silly gunzTarPerm extractEntry src/platformcompat.hh
96 silly gunzTarPerm extractEntry src/util.cc
97 silly gunzTarPerm extractEntry src/util.hh
98 silly gunzTarPerm extractEntry examples/basic_heapdiff.js
99 silly gunzTarPerm extractEntry examples/do_nothing_server.js
100 silly gunzTarPerm extractEntry examples/slightly_leaky.js
101 verbose write writing to /Users/USERNAME/PATH/PATH/node_modules/memwatch/package.json
102 info preinstall memwatch@0.2.2
103 verbose readDependencies loading dependencies from /Users/USERNAME/PATH/PATH/node_modules/memwatch/package.json
104 verbose readDependencies loading dependencies from /Users/USERNAME/PATH/PATH/node_modules/memwatch/package.json
105 silly install resolved []
106 verbose about to build /Users/USERNAME/PATH/PATH/node_modules/memwatch
107 info build /Users/USERNAME/PATH/PATH/node_modules/memwatch
108 info linkStuff memwatch@0.2.2
109 silly linkStuff memwatch@0.2.2 has /Users/USERNAME/PATH/PATH/node_modules as its parent node_modules
110 verbose linkBins memwatch@0.2.2
111 verbose linkMans memwatch@0.2.2
112 verbose rebuildBundles memwatch@0.2.2
113 info install memwatch@0.2.2
114 verbose unsafe-perm in lifecycle true
115 info memwatch@0.2.2 Failed to exec install script
116 verbose unlock done using /Users/USERNAME/.npm/_locks/memwatch-880cc2a1e8439e30.lock for /Users/USERNAME/PATH/PATH/node_modules/memwatch
117 verbose stack Error: memwatch@0.2.2 install: `node-gyp rebuild`
117 verbose stack Exit status 1
117 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
117 verbose stack     at EventEmitter.emit (events.js:110:17)
117 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
117 verbose stack     at ChildProcess.emit (events.js:110:17)
117 verbose stack     at maybeClose (child_process.js:1015:16)
117 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
118 verbose pkgid memwatch@0.2.2
119 verbose cwd /Users/USERNAME/PATH/PATH
120 error Darwin 14.5.0
121 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "memwatch"
122 error node v0.12.7
123 error npm  v2.11.3
124 error code ELIFECYCLE
125 error memwatch@0.2.2 install: `node-gyp rebuild`
125 error Exit status 1
126 error Failed at the memwatch@0.2.2 install script 'node-gyp rebuild'.
126 error This is most likely a problem with the memwatch package,
126 error not with npm itself.
126 error Tell the author that this fails on your system:
126 error     node-gyp rebuild
126 error You can get their info via:
126 error     npm owner ls memwatch
126 error There is likely additional logging output above.
127 verbose exit [ 1, true ]
128 verbose unbuild node_modules/memwatch
129 info preuninstall memwatch@0.2.2
130 info uninstall memwatch@0.2.2
131 verbose unbuild rmStuff memwatch@0.2.2 from /Users/USERNAME/PATH/PATH/node_modules
132 info postuninstall memwatch@0.2.2
133 silly gentlyRm /Users/USERNAME/PATH/PATH/node_modules/memwatch is being purged from base /Users/USERNAME/PATH/PATH
134 verbose gentlyRm don't care about contents; nuking /Users/USERNAME/PATH/PATH/node_modules/memwatch
135 silly vacuum-fs purging /Users/USERNAME/PATH/PATH/node_modules/memwatch
136 silly vacuum-fs quitting because other entries in /Users/USERNAME/PATH/PATH/node_modules
``````

sensitive information redacted

**Comment by brentpayne** [comment]
had the same issue

**Comment by JiaJiaJiang** [comment]
try node 0.10.x
new node has changed its interface

**Comment by chisleu** [comment]
```
11:16:09 ~$ node --version
v0.12.7
```

Or are you saying to downgrade? That is impossible for us because we are using ES6. :(

**Comment by JiaJiaJiang** [comment]
@chisleu the same issue.Someone told me try node 0.10.x,and it works.

**Comment by chisleu** [comment]
Yes, I see this isn't ported to .12 yet. I also found a PR that fixes this, but it apparently breaks travis so it is held up for now.

**Comment by ChadMartinson** [comment]
Has anyone resolved this issue yet?

**Comment by creeperyang** [comment]
Same issue. So any plan to support `v0.12.x`?

**Comment by chisleu** [comment]
I recommend using the requests library. I is far more popular. This doesn't seem maintained.

Leaving this open, but I'm unsubscribed.

**Comment by sheldonkreger** [comment]
Running into the same issue with Node 4.2.2 as well.

**Comment by creeperyang** [comment]
I found **[memwatch-next](https://github.com/marcominetti/node-memwatch)**  that enhances **compatibility**!

I tested `node 0.12.x` successfully and it looks like support:

``` bash
node_js:
 - "0.10"
 - "0.11"
 - "0.12"
 - "iojs-v1.0"
 - "iojs-v1.1"
 - "iojs-v1.2"
 - "iojs-v1.3"
 - "iojs-v1.4"
 - "iojs-v1.5"
 - "iojs-v1.6"
 - "iojs-v1.7"
 - "iojs-v1.8"
 - "iojs-v2.0"
 - "iojs-v3.0"
```

Maybe `node 4.x` is supported too. Have a try and give up the no longer maintainable `node-memwatch` here.

**Comment by JiaJiaJiang** [comment]
@creeperyang ok,let's move

**Comment by jcollum** [comment]
Node 4.4 on OSX: memwatch will not install, memwatch-next will.

**Comment by designeng** [comment]
Running into the same issue with `Node v5.11.1` & `npm version 3.8.6`.

**Comment by donghanji** [comment]
use  memwatch-next  ,see @creeperyang
