### ISSUE TITLE
Module did not self register

### ISSUE THREAD

**Issue by dvli2007** [lloyd/node-memwatch#74]
I've been running into the following issue with my `memwatch-next` installation. My `memwatch-next` version is `0.2.10`, and I'm running node `v5.4.1` and npm `3.3.12` on an Ubuntu 14.04.1 machine.

```
root@localhost:/opt/app# node ./bin/www
Log config loaded from log.cfg
/opt/app/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:422:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/opt/app/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/opt/app/node_modules/memwatch-next/include.js:2:28)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
```

I've tried `npm rebuild`, as well as clearing my `node_modules` directory and runninng `npm install` again. No luck so far.

**Comment by guypaskar** [comment]
+1

**Comment by Gouayave** [comment]
Test in your project package:
npm rebuild

**Comment by nphias** [comment]
I get a similar error... i think there is a problem with the bindings.js
anyone fix this?
https://github.com/marcominetti/node-memwatch/issues/22

**Comment by RaghavendhraK** [comment]
+1
