### ISSUE TITLE
[SOLVED] npm install error

### ISSUE THREAD

**Issue by Nomia** [lloyd/node-memwatch#79]
# UPDATE: problem solved

For those who has the same install error, try
`npm install memwatch-next`
# ORIGINAL ERROR

Hi, I love the design of your work, but just cannot install :<  

$ npm install memwatch --save-dev
|

> memwatch@0.2.2 install /Users/Vincent/Desktop/wxbot-node/node_modules/memwatch
> node-gyp rebuild

gyp: /Users/Vincent/.node-gyp/4.2.3/common.gypi not found (cwd: /Users/Vincent/Desktop/wxbot-node/node_modules/memwatch) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/cnpm/node_modules/pangyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/pangyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Vincent/Desktop/wxbot-node/node_modules/memwatch
gyp ERR! node -v v4.2.3
gyp ERR! pangyp -v v2.1.0
gyp ERR! not ok
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/Users/Vincent/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=/Users/Vincent/.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=/usr/local/lib/node_modules/cnpm/node_modules/pangyp/bin/node-gyp.js" "install" "memwatch" "--save-dev"
npm ERR! node v4.2.3
npm ERR! npm  v2.13.5
npm ERR! code ELIFECYCLE

npm ERR! memwatch@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the memwatch@0.2.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the memwatch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls memwatch
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Vincent/Desktop/wxbot-node/npm-debug.log
# Here is the log:

0 info it worked if it ends with ok
1 verbose cli   '--node-gyp=/usr/local/lib/node_modules/cnpm/node_modules/pangyp/bin/node-gyp.js',
1 verbose cli   'install',
1 verbose cli   'memwatch',
1 verbose cli   '--save-dev' ]
2 info using npm@2.13.5
3 info using node@v4.2.3
4 verbose install initial load of /Users/Vincent/Desktop/wxbot-node/package.json
5 verbose installManyTop reading scoped package data from /Users/Vincent/Desktop/wxbot-node/node_modules/babel-eslint/package.json
6 verbose installManyTop reading scoped package data from /Users/Vincent/Desktop/wxbot-node/node_modules/electron/package.json
7 verbose installManyTop reading scoped package data from /Users/Vincent/Desktop/wxbot-node/node_modules/electron-packager/package.json
8 verbose installManyTop reading scoped package data from /Users/Vincent/Desktop/wxbot-node/node_modules/electron-prebuilt/package.json
9 verbose installManyTop reading scoped package data from /Users/Vincent/Desktop/wxbot-node/node_modules/eslint/package.json
10 verbose installManyTop reading scoped package data from /Users/Vincent/Desktop/wxbot-node/node_modules/eslint-config-airbnb/package.json
11 verbose installManyTop reading scoped package data from /Users/Vincent/Desktop/wxbot-node/node_modules/eslint-plugin-import/package.json
12 verbose installManyTop reading scoped package data from /Users/Vincent/Desktop/wxbot-node/node_modules/eslint-plugin-jsx-a11y/package.json
13 verbose installManyTop reading scoped package data from /Users/Vincent/Desktop/wxbot-node/node_modules/eslint-plugin-react/package.json
14 verbose installManyTop reading scoped package data from /Users/Vincent/Desktop/wxbot-node/node_modules/jquery/package.json
15 verbose installManyTop reading scoped package data from /Users/Vincent/Desktop/wxbot-node/node_modules/jsdom/package.json
16 verbose installManyTop reading scoped package data from /Users/Vincent/Desktop/wxbot-node/node_modules/md5/package.json
17 verbose installManyTop reading scoped package data from /Users/Vincent/Desktop/wxbot-node/node_modules/moment/package.json
18 verbose installManyTop reading scoped package data from /Users/Vincent/Desktop/wxbot-node/node_modules/pinyin/package.json
19 verbose readDependencies loading dependencies from /Users/Vincent/Desktop/wxbot-node/package.json
20 silly cache add args [ 'memwatch', null ]
21 verbose cache add spec memwatch
22 silly cache add parsed spec Result {
22 silly cache add   raw: 'memwatch',
22 silly cache add   scope: null,
22 silly cache add   name: 'memwatch',
22 silly cache add   rawSpec: '',
22 silly cache add   spec: '_',
22 silly cache add   type: 'range' }
23 silly addNamed memwatch@_
24 verbose addNamed "_" is a valid semver range for memwatch
25 silly addNameRange { name: 'memwatch', range: '_', hasData: false }
26 silly mapToRegistry name memwatch
27 silly mapToRegistry using default registry
28 silly mapToRegistry registry https://registry.npm.taobao.org/
29 silly mapToRegistry uri https://registry.npm.taobao.org/memwatch
30 verbose addNameRange registry:https://registry.npm.taobao.org/memwatch not in flight; fetching
31 verbose request uri https://registry.npm.taobao.org/memwatch
32 verbose request no auth needed
33 info attempt registry request try #1 at 11:12:05 AM
34 verbose request id c6ef7f183f5b68e8
35 http request GET https://registry.npm.taobao.org/memwatch
36 http 200 https://registry.npm.taobao.org/memwatch
37 silly get cb [ 200,
37 silly get   { date: 'Thu, 20 Oct 2016 03:12:27 GMT',
37 silly get     'content-type': 'application/json; charset=utf-8',
37 silly get     'content-length': '15896',
37 silly get     connection: 'keep-alive',
37 silly get     'x-current-requests': '1',
37 silly get     etag: '"3e18-EFKuKdOQBRC+ImSr8doidw"',
37 silly get     'x-readtime': '14' } ]
38 verbose get saving memwatch to /Users/Vincent/.cnpm/registry.npm.taobao.org/memwatch/.cache.json
39 silly addNameRange number 2 { name: 'memwatch', range: '_', hasData: true }
40 silly addNameRange versions [ 'memwatch',
40 silly addNameRange   [ '0.2.2',
40 silly addNameRange     '0.2.1',
40 silly addNameRange     '0.2.0',
40 silly addNameRange     '0.1.5',
40 silly addNameRange     '0.1.4',
40 silly addNameRange     '0.1.3',
40 silly addNameRange     '0.1.2',
40 silly addNameRange     '0.1.1',
40 silly addNameRange     '0.1.0' ] ]
41 silly addNamed memwatch@0.2.2
42 verbose addNamed "0.2.2" is a plain semver version for memwatch
43 silly mapToRegistry name memwatch
44 silly mapToRegistry using default registry
45 silly mapToRegistry registry https://registry.npm.taobao.org/
46 silly mapToRegistry uri https://registry.npm.taobao.org/memwatch
47 verbose addRemoteTarball https://registry.npm.taobao.org/memwatch/download/memwatch-0.2.2.tgz not in flight; adding
48 verbose addRemoteTarball [ 'https://registry.npm.taobao.org/memwatch/download/memwatch-0.2.2.tgz',
48 verbose addRemoteTarball   '779e8cd982532b6221b6ed1c1269098bee16f92c' ]
49 info retry fetch attempt 1 at 11:12:28 AM
50 info attempt registry request try #1 at 11:12:28 AM
51 http fetch GET https://registry.npm.taobao.org/memwatch/download/memwatch-0.2.2.tgz
52 http fetch 200 https://registry.npm.taobao.org/memwatch/download/memwatch-0.2.2.tgz
53 silly fetchAndShaCheck shasum 779e8cd982532b6221b6ed1c1269098bee16f92c
54 verbose addTmpTarball /var/folders/xf/pd1xlwbs0dx2zns9r3cpw6sm0000gn/T/npm-14498-ac4651cb/registry.npm.taobao.org/memwatch/download/memwatch-0.2.2.tgz not in flight; adding
55 verbose addTmpTarball already have metadata; skipping unpack for memwatch@0.2.2
56 silly cache afterAdd memwatch@0.2.2
57 verbose afterAdd /Users/Vincent/.cnpm/memwatch/0.2.2/package/package.json not in flight; writing
58 verbose afterAdd /Users/Vincent/.cnpm/memwatch/0.2.2/package/package.json written
59 silly install resolved [ { name: 'memwatch',
59 silly install resolved     description: 'Keep an eye on your memory usage, and discover and isolate leaks.',
59 silly install resolved     version: '0.2.2',
59 silly install resolved     author: { name: 'Lloyd Hilaiel', url: 'http://lloyd.io' },
59 silly install resolved     engines: { node: '>= 0.6.0' },
59 silly install resolved     repository:
59 silly install resolved      { type: 'git',
59 silly install resolved        url: 'https://github.com/lloyd/node-memwatch.git' },
59 silly install resolved     main: 'include.js',
59 silly install resolved     licenses: [ [Object] ],
59 silly install resolved     bugs: { url: 'https://github.com/lloyd/node-memwatch/issues' },
59 silly install resolved     scripts: { install: 'node-gyp rebuild', test: 'mocha tests' },
59 silly install resolved     devDependencies: { mocha: '1.2.2', should: '0.6.3', 'node-gyp': '0.5.7' },
59 silly install resolved     contributors: [ [Object], [Object], [Object] ],
59 silly install resolved     readmeFilename: 'README.md',
59 silly install resolved     _id: 'memwatch@0.2.2',
59 silly install resolved     dist:
59 silly install resolved      { shasum: '779e8cd982532b6221b6ed1c1269098bee16f92c',
59 silly install resolved        size: 11266,
59 silly install resolved        noattachment: false,
59 silly install resolved        tarball: 'http://registry.npm.taobao.org/memwatch/download/memwatch-0.2.2.tgz' },
59 silly install resolved     _from: 'memwatch@_',
59 silly install resolved     _npmVersion: '1.2.14',
59 silly install resolved     _npmUser: { name: 'lloyd', email: 'lloyd@hilaiel.com' },
59 silly install resolved     maintainers: [ [Object] ],
59 silly install resolved     directories: {},
59 silly install resolved     publish_time: 1363215719219,
59 silly install resolved     _cnpm_publish_time: 1363215719219,
59 silly install resolved     _shasum: '779e8cd982532b6221b6ed1c1269098bee16f92c',
59 silly install resolved     _resolved: 'https://registry.npm.taobao.org/memwatch/download/memwatch-0.2.2.tgz' } ]
60 info install memwatch@0.2.2 into /Users/Vincent/Desktop/wxbot-node
61 info installOne memwatch@0.2.2
62 verbose installOne of memwatch to /Users/Vincent/Desktop/wxbot-node not in flight; installing
63 verbose lock using /Users/Vincent/.cnpm/_locks/memwatch-b601871eb72ec4dc.lock for /Users/Vincent/Desktop/wxbot-node/node_modules/memwatch
64 silly install write writing memwatch 0.2.2 to /Users/Vincent/Desktop/wxbot-node/node_modules/memwatch
65 verbose unbuild node_modules/memwatch
66 silly gentlyRm /Users/Vincent/Desktop/wxbot-node/node_modules/memwatch is being purged from base /Users/Vincent/Desktop/wxbot-node
67 verbose gentlyRm don't care about contents; nuking /Users/Vincent/Desktop/wxbot-node/node_modules/memwatch
68 verbose tar unpack /Users/Vincent/.cnpm/memwatch/0.2.2/package.tgz
69 verbose tar unpacking to /Users/Vincent/Desktop/wxbot-node/node_modules/memwatch
70 silly gentlyRm /Users/Vincent/Desktop/wxbot-node/node_modules/memwatch is being purged
71 verbose gentlyRm don't care about contents; nuking /Users/Vincent/Desktop/wxbot-node/node_modules/memwatch
72 silly gunzTarPerm modes [ '755', '644' ]
73 silly gunzTarPerm extractEntry package.json
74 silly gunzTarPerm extractEntry .npmignore
75 silly gunzTarPerm extractEntry README.md
76 silly gunzTarPerm extractEntry tests.js
77 silly gunzTarPerm extractEntry foo.js
78 silly gunzTarPerm extractEntry include.js
79 silly gunzTarPerm extractEntry .travis.yml
80 silly gunzTarPerm extractEntry ChangeLog
81 silly gunzTarPerm extractEntry #wscript#
82 silly gunzTarPerm extractEntry binding.gyp
83 silly gunzTarPerm extractEntry src/heapdiff.cc
84 silly gunzTarPerm extractEntry src/heapdiff.hh
85 silly gunzTarPerm extractEntry src/init.cc
86 silly gunzTarPerm extractEntry src/memwatch.cc
87 silly gunzTarPerm extractEntry src/memwatch.hh
88 silly gunzTarPerm extractEntry src/platformcompat.hh
89 silly gunzTarPerm extractEntry src/util.cc
90 silly gunzTarPerm extractEntry src/util.hh
91 silly gunzTarPerm extractEntry examples/basic_heapdiff.js
92 silly gunzTarPerm extractEntry examples/do_nothing_server.js
93 silly gunzTarPerm extractEntry examples/slightly_leaky.js
94 verbose write writing to /Users/Vincent/Desktop/wxbot-node/node_modules/memwatch/package.json
95 info preinstall memwatch@0.2.2
96 verbose readDependencies loading dependencies from /Users/Vincent/Desktop/wxbot-node/node_modules/memwatch/package.json
97 verbose readDependencies loading dependencies from /Users/Vincent/Desktop/wxbot-node/node_modules/memwatch/package.json
98 silly install resolved []
99 verbose about to build /Users/Vincent/Desktop/wxbot-node/node_modules/memwatch
100 info build /Users/Vincent/Desktop/wxbot-node/node_modules/memwatch
101 info linkStuff memwatch@0.2.2
102 silly linkStuff memwatch@0.2.2 has /Users/Vincent/Desktop/wxbot-node/node_modules as its parent node_modules
103 verbose linkBins memwatch@0.2.2
104 verbose linkMans memwatch@0.2.2
105 verbose rebuildBundles memwatch@0.2.2
106 info install memwatch@0.2.2
107 verbose unsafe-perm in lifecycle true
108 info memwatch@0.2.2 Failed to exec install script
109 verbose unlock done using /Users/Vincent/.cnpm/_locks/memwatch-b601871eb72ec4dc.lock for /Users/Vincent/Desktop/wxbot-node/node_modules/memwatch
110 verbose stack Error: memwatch@0.2.2 install: `node-gyp rebuild`
110 verbose stack Exit status 1
110 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/utils/lifecycle.js:214:16)
110 verbose stack     at emitTwo (events.js:87:13)
110 verbose stack     at EventEmitter.emit (events.js:172:7)
110 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/utils/spawn.js:24:14)
110 verbose stack     at emitTwo (events.js:87:13)
110 verbose stack     at ChildProcess.emit (events.js:172:7)
110 verbose stack     at maybeClose (internal/child_process.js:818:16)
110 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
111 verbose pkgid memwatch@0.2.2
112 verbose cwd /Users/Vincent/Desktop/wxbot-node
113 error Darwin 16.0.0
114 error argv "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/Users/Vincent/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=/Users/Vincent/.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=/usr/local/lib/node_modules/cnpm/node_modules/pangyp/bin/node-gyp.js" "install" "memwatch" "--save-dev"
115 error node v4.2.3
116 error npm  v2.13.5
117 error code ELIFECYCLE
118 error memwatch@0.2.2 install: `node-gyp rebuild`
118 error Exit status 1
119 error Failed at the memwatch@0.2.2 install script 'node-gyp rebuild'.
119 error This is most likely a problem with the memwatch package,
119 error not with npm itself.
119 error Tell the author that this fails on your system:
119 error     node-gyp rebuild
119 error You can get their info via:
119 error     npm owner ls memwatch
119 error There is likely additional logging output above.
120 verbose exit [ 1, true ]
121 verbose unbuild node_modules/memwatch
122 info preuninstall memwatch@0.2.2
123 info uninstall memwatch@0.2.2
124 verbose unbuild rmStuff memwatch@0.2.2 from /Users/Vincent/Desktop/wxbot-node/node_modules
125 info postuninstall memwatch@0.2.2
126 silly gentlyRm /Users/Vincent/Desktop/wxbot-node/node_modules/memwatch is being purged from base /Users/Vincent/Desktop/wxbot-node
127 verbose gentlyRm don't care about contents; nuking /Users/Vincent/Desktop/wxbot-node/node_modules/memwatch
128 silly vacuum-fs purging /Users/Vincent/Desktop/wxbot-node/node_modules/memwatch
129 silly vacuum-fs quitting because other entries in /Users/Vincent/Desktop/wxbot-node/node_modules

**Comment by ksami** [comment]
Thank you for coming back to update!

**Comment by malipraful** [comment]
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 2.6.32-642.13.1.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! memwatch@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the memwatch@0.2.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the memwatch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs memwatch
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls memwatch
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by piampri** [comment]
What was the solution here ???

**Comment by Nomia** [comment]
![image](https://user-images.githubusercontent.com/1707818/48453112-06abfc00-e7ed-11e8-91ce-1a8f8434c7f2.png)
@piampri

**Comment by glensc** [comment]
memwatch-next also dead

**Comment by wolf-yuan-6115** [comment]
> memwatch-next also dead

yes

**Comment by wolf-yuan-6115** [comment]
> ![image](https://user-images.githubusercontent.com/1707818/48453112-06abfc00-e7ed-11e8-91ce-1a8f8434c7f2.png)
> @piampri 

Hey...
memwatch-next is dead too...

**Comment by minggangLu** [comment]
the same error, neither memwatch nor memwatch-next can work

**Comment by missak-boyajian** [comment]
Have the same issue.

**Comment by HiptJo** [comment]
same here

**Comment by nikakhachi** [comment]
Same here

``$ npm i memwatch-next --save-dev``

Doesn't work

**Comment by Camuvingian** [comment]
And me too.

**Comment by sts-lauri** [comment]
Same here. Windows 10 build errors on https://github.com/lloyd/node-memwatch and https://github.com/airbnb/node-memwatch both

**Comment by BBC6BAE9** [comment]
And me too.

**Comment by catcatcatcatcatcatcatcatcatcat** [comment]
yuck. now how will I ever finger out my memory leeks 🥬 ?

**Comment by BBC6BAE9** [comment]
Finally I wrote a simple FSM by myself，I hope this will help you.

Russell ***@***.***> 于2023年5月26日周五 06:14写道：
