### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by narayanmp** [lloyd/node-memwatch#80]
Getting this install error. Tried memwatch-next, same error. 

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found.
Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:
\Users\nmangala\Documents\GitHub\wm-trans-status\node_modules\memwatch\build\memwatch.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\nmangala\Documents\GitHub\wm-trans-status\node_modules\memwatch
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "memwatch"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! memwatch@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the memwatch@0.2.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the memwatch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs memwatch
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls memwatch
npm ERR! There is likely additional logging output above.

[npm-debug.zip](https://github.com/lloyd/node-memwatch/files/622487/npm-debug.zip)

**Comment by rajeshshegokar111** [comment]
hi..I am also getting error while installing memwatch package.. tried manually also but no luck. getting npm rebuild issue/error

**Comment by rajeshshegokar111** [comment]
![memwatch](https://cloud.githubusercontent.com/assets/4987341/20764011/74cf6c80-b752-11e6-8ba0-01046874348d.PNG)

**Comment by jwerre** [comment]
This worked for me:

    rm -rf node_modules #or whatever the Windows equivalent is
    npm cache clean
    npm install

**Comment by jwerre** [comment]
Also, you might want to use `memwatch-next`

**Comment by geertbrit** [comment]
@jwerre so 'memwatch-next' is 'memwatch' but for newer node versions? Is there a doc somewhere that explains this?
