### ISSUE TITLE
installing Memwatch

### ISSUE THREAD

**Issue by malipraful** [lloyd/node-memwatch#82]
npm ERR! Failed at the memwatch-next@0.3.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the memwatch-next package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs memwatch-next
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls memwatch-next
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by danielbaak** [comment]
I am also getting a bunch of errors on install.

It appears as if either my C compiler uses a different standard or the code contains errors.

```
make: Entering directory '/home/u/Projects/refreshable/node_modules/memwatch/build'
  CXX(target) Release/obj.target/memwatch/src/heapdiff.o
In file included from ../src/heapdiff.cc:5:0:
../src/heapdiff.hh:15:5: error: expected class-name before ‘{’ token
     {
     ^
../src/heapdiff.hh:19:53: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> New( const v8::Arguments& args );
                                                     ^
../src/heapdiff.hh:20:53: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> End( const v8::Arguments& args );
                                                     ^
../src/heapdiff.cc: In constructor ‘heapdiff::HeapDiff::HeapDiff()’:
../src/heapdiff.cc:30:34: error: class ‘heapdiff::HeapDiff’ does not have any field named ‘ObjectWrap’
 heapdiff::HeapDiff::HeapDiff() : ObjectWrap(), before(NULL), after(NULL),
                                  ^
```

[2017-05-19T08_47_33_077Z-debug.txt](https://github.com/lloyd/node-memwatch/files/1013627/2017-05-19T08_47_33_077Z-debug.txt)

**Comment by cphoover** [comment]
same issue ^^

**Comment by WellerQu** [comment]
same issue : (

**Comment by sansabaggins** [comment]
same issue....

**Comment by mryjnlrnz** [comment]
C:\xampp\htdocs\folder\node_modules\memwatch>if not defined npm_config_node_gyp (node "C:\Users\user\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\xampp\htdocs\folder\node_modules\memwatch\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\xampp\htdocs\folder\node_modules\memwatch
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! memwatch@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the memwatch@0.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\debug.log

**Comment by mehdijazayeri3000** [comment]
same issue

**Comment by Parziphal** [comment]
Check #79, the solution is to install `memwatch-next` instead of just `memwatch`. Logically, in your script you will have to `require('memwatch-next')` instead of just `memwatch`.

Here's the repo: https://github.com/marcominetti/node-memwatch

**Comment by NextZeus** [comment]
I don't think anyone is maintaining this repo. @Parziphal thanks
